/**********************************************************************

	--- Qt Architect generated file ---

	File: AdjQueryDlgData.h
	Last generated: Sat Oct 13 15:52:44 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef AdjQueryDlgData_included
#define AdjQueryDlgData_included

#include <compat_2x.h> // string type macro 

#ifdef EA_KDE2x
#define EA_SPINBOX_H <qspinbox.h>
#define EA_SPINBOX   QSpinBox
#else
#define EA_SPINBOX_H <kspinbox.h>
#define EA_SPINBOX   KSpinBox
#endif
#include "QueryDlgBase.h"
#include <qlabel.h>
#include <qpushbutton.h>
#include <qlineedit.h>
#include "MyProgress.h"

class AdjQueryDlgData : public QueryDlgBase
{
    Q_OBJECT

public:

    AdjQueryDlgData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

//  virtual ~AdjQueryDlgData();

public slots:


protected slots:


protected:
    QLineEdit* lev1Field;
    QLineEdit* lev2Field;
    QLineEdit* lev3Field;
    QPushButton* b_edit;
    QPushButton* show_all;
    QPushButton* verify;
    QPushButton* know_it;
    QPushButton* dont_know;
    QPushButton* stop_it;
    QPushButton* options;
    QLabel* lev1Label;
    QLabel* lev2Label;
    QLabel* lev3Label;
    QLabel* countlabel;
    MyProgressBar* countbar;
    QLabel* timelabel;
    MyProgressBar* timebar;
    QLabel* progCount;

};

#endif // AdjQueryDlgData_included
