/**********************************************************************

	--- Qt Architect generated file ---

	File: AdjQueryDlgData.cpp
	Last generated: Thu Oct 4 17:21:51 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "AdjQueryDlgData.h"

#define Inherited QueryDlgBase

#include <qlabel.h>
#include <qbuttongroup.h>
#include <kapp.h>  // i18n macro

#include <compat_2x.h> // string type macro 


AdjQueryDlgData::AdjQueryDlgData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	QButtonGroup* qtarch_ButtonGroup_4;
	qtarch_ButtonGroup_4 = new QButtonGroup( this, "ButtonGroup_4" );
	qtarch_ButtonGroup_4->setGeometry( 30, 30, 400, 350 );
	qtarch_ButtonGroup_4->setFrameStyle( 49 );
	qtarch_ButtonGroup_4->setTitle( "" );
	qtarch_ButtonGroup_4->setAlignment( 1 );

	QButtonGroup* qtarch_ButtonGroup_1;
	qtarch_ButtonGroup_1 = new QButtonGroup( this, "ButtonGroup_1" );
	qtarch_ButtonGroup_1->setGeometry( 10, 10, 580, 390 );
	qtarch_ButtonGroup_1->setFrameStyle( 49 );
	qtarch_ButtonGroup_1->setTitle( "" );
	qtarch_ButtonGroup_1->setAlignment( 1 );

	QLabel* qtarch_Label_14;
	qtarch_Label_14 = new QLabel( this, "Label_14" );
	qtarch_Label_14->setGeometry( 60, 40, 320, 30 );
	{
		QFont font( "helvetica", 12, 75, 0 );
		font.setStyleHint( (QFont::StyleHint)0 );
		font.setCharSet( (QFont::CharSet)0 );
		qtarch_Label_14->setFont( font );
	}
	qtarch_Label_14->setFrameStyle( 0 );
	qtarch_Label_14->setText( i18n( "Complete comparison expressions:" ));
	qtarch_Label_14->setAlignment( 289 );

	lev1Field = new QLineEdit( this, "LineEdit_3" );
	lev1Field->setGeometry( 140, 80, 140, 30 );
	lev1Field->setText( "" );
	lev1Field->setMaxLength( 32767 );

	lev2Field = new QLineEdit( this, "LineEdit_4" );
	lev2Field->setGeometry( 140, 140, 140, 30 );
	lev2Field->setText( "" );
	lev2Field->setMaxLength( 32767 );

	lev3Field = new QLineEdit( this, "LineEdit_5" );
	lev3Field->setGeometry( 140, 200, 140, 30 );
	lev3Field->setText( "" );
	lev3Field->setMaxLength( 32767 );

	b_edit = new QPushButton( this, "PushButton_6" );
	b_edit->setGeometry( 300, 140, 110, 30 );
	b_edit->setText( i18n( "&Edit" ));

	show_all = new QPushButton( this, "PushButton_2" );
	show_all->setGeometry( 80, 280, 110, 30 );
	show_all->setText( i18n( "Show &all" ));

	verify = new QPushButton( this, "PushButton_3" );
	verify->setGeometry( 80, 330, 110, 30 );
	verify->setText( i18n( "&Verify" ));

	know_it = new QPushButton( this, "PushButton_5" );
	know_it->setGeometry( 260, 280, 110, 30 );
	know_it->setText( i18n( "I &know it" ));

	dont_know = new QPushButton( this, "PushButton_4" );
	dont_know->setGeometry( 260, 330, 110, 30 );
	dont_know->setText( i18n( "&Don't know" ));

	stop_it = new QPushButton( this, "PushButton_7" );
	stop_it->setGeometry( 460, 280, 100, 30 );
	stop_it->setText( i18n( "&Stop query" ));

	options = new QPushButton( this, "PushButton_8" );
	options->setGeometry( 460, 330, 100, 30 );
	options->setText( i18n( "&Options" ));

	lev1Label = new QLabel( this, "Label_11" );
	lev1Label->setGeometry( 60, 80, 70, 30 );
	lev1Label->setFrameStyle( 0 );
	lev1Label->setText( i18n( "Level &1" ));
	lev1Label->setAlignment( 289 );

	lev2Label = new QLabel( this, "Label_12" );
	lev2Label->setGeometry( 60, 140, 70, 30 );
	lev2Label->setFrameStyle( 0 );
	lev2Label->setText( i18n( "Level &2" ));
	lev2Label->setAlignment( 289 );

	lev3Label = new QLabel( this, "Label_13" );
	lev3Label->setGeometry( 60, 200, 70, 30 );
	lev3Label->setFrameStyle( 0 );
	lev3Label->setText( i18n( "Level &3" ));
	lev3Label->setAlignment( 289 );

	QButtonGroup* qtarch_ButtonGroup_5;
	qtarch_ButtonGroup_5 = new QButtonGroup( this, "ButtonGroup_5" );
	qtarch_ButtonGroup_5->setGeometry( 440, 20, 130, 170 );
	qtarch_ButtonGroup_5->setFrameStyle( 49 );
	qtarch_ButtonGroup_5->setTitle( i18n( "Progress" ));
	qtarch_ButtonGroup_5->setAlignment( 1 );

	countlabel = new QLabel( this, "Label_21" );
	countlabel->setGeometry( 450, 40, 100, 20 );
	countlabel->setFrameStyle( 0 );
	countlabel->setText( i18n( "Count" ));
	countlabel->setAlignment( 289 );

	countbar = new MyProgressBar( this, "User_1" );
	countbar->setGeometry( 450, 60, 110, 30 );

	timelabel = new QLabel( this, "Label_22" );
	timelabel->setGeometry( 450, 100, 100, 20 );
	timelabel->setFrameStyle( 0 );
	timelabel->setText( i18n( "Time" ));
	timelabel->setAlignment( 289 );

	timebar = new MyProgressBar( this, "User_2" );
	timebar->setGeometry( 450, 120, 110, 30 );

	QLabel* qtarch_Label_9;
	qtarch_Label_9 = new QLabel( this, "Label_9" );
	qtarch_Label_9->setGeometry( 450, 160, 60, 20 );
	qtarch_Label_9->setFrameStyle( 0 );
	qtarch_Label_9->setText( i18n( "Cycle:" ));
	qtarch_Label_9->setAlignment( 289 );

	progCount = new QLabel( this, "Label_10" );
	progCount->setGeometry( 530, 160, 20, 20 );
	progCount->setFrameStyle( 0 );
	progCount->setText( i18n( "1" ));
	progCount->setAlignment( 289 );




	resize( 600,410 );
}


//AdjQueryDlgData::~AdjQueryDlgData()
//{
//}
