/**********************************************************************

	--- Qt Architect generated file ---

	File: ArtQueryDlgData.cpp
	Last generated: Thu Oct 4 17:21:56 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "ArtQueryDlgData.h"

#define Inherited QueryDlgBase

#include <qlabel.h>
#include <qbuttongroup.h>
#include <kapp.h>  // i18n macro

#include <compat_2x.h> // string type macro 


ArtQueryDlgData::ArtQueryDlgData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	QButtonGroup* qtarch_ButtonGroup_1;
	qtarch_ButtonGroup_1 = new QButtonGroup( this, "ButtonGroup_1" );
	qtarch_ButtonGroup_1->setGeometry( 10, 10, 580, 390 );
	qtarch_ButtonGroup_1->setFrameStyle( 49 );
	qtarch_ButtonGroup_1->setTitle( "" );
	qtarch_ButtonGroup_1->setAlignment( 1 );

	art_group = new QButtonGroup( this, "ButtonGroup_4" );
	art_group->setGeometry( 30, 20, 400, 360 );
	art_group->setFrameStyle( 49 );
	art_group->setTitle( "" );
	art_group->setAlignment( 1 );

	rb_fem = new QRadioButton( this, "RadioButton_1" );
	rb_fem->setGeometry( 60, 130, 220, 20 );
	rb_fem->setText( i18n( "&female" ));
	rb_fem->setChecked( FALSE );

	male = new QRadioButton( this, "RadioButton_2" );
	male->setGeometry( 60, 170, 220, 20 );
	male->setText( i18n( "&male" ));
	male->setChecked( FALSE );

	natural = new QRadioButton( this, "RadioButton_3" );
	natural->setGeometry( 60, 210, 220, 20 );
	natural->setText( i18n( "&neutral" ));
	natural->setChecked( FALSE );

	b_edit = new QPushButton( this, "PushButton_6" );
	b_edit->setGeometry( 300, 160, 110, 30 );
	b_edit->setText( i18n( "&Edit" ));

	show_all = new QPushButton( this, "PushButton_2" );
	show_all->setGeometry( 80, 270, 110, 30 );
	show_all->setText( i18n( "Show &all" ));

	verify = new QPushButton( this, "PushButton_3" );
	verify->setGeometry( 80, 320, 110, 30 );
	verify->setText( i18n( "&Verify" ));

	know_it = new QPushButton( this, "PushButton_5" );
	know_it->setGeometry( 270, 270, 110, 30 );
	know_it->setText( i18n( "I &know it" ));

	dont_know = new QPushButton( this, "PushButton_4" );
	dont_know->setGeometry( 270, 320, 110, 30 );
	dont_know->setText( i18n( "&Don't know" ));

	stop_it = new QPushButton( this, "PushButton_7" );
	stop_it->setGeometry( 460, 270, 100, 30 );
	stop_it->setText( i18n( "&Stop query" ));

	options = new QPushButton( this, "PushButton_8" );
	options->setGeometry( 460, 320, 100, 30 );
	options->setText( i18n( "&Options" ));

	QButtonGroup* qtarch_ButtonGroup_5;
	qtarch_ButtonGroup_5 = new QButtonGroup( this, "ButtonGroup_5" );
	qtarch_ButtonGroup_5->setGeometry( 440, 20, 130, 170 );
	qtarch_ButtonGroup_5->setFrameStyle( 49 );
	qtarch_ButtonGroup_5->setTitle( i18n( "Progress" ));
	qtarch_ButtonGroup_5->setAlignment( 1 );

	countlabel = new QLabel( this, "Label_13" );
	countlabel->setGeometry( 450, 40, 100, 20 );
	countlabel->setFrameStyle( 0 );
	countlabel->setText( i18n( "Count" ));
	countlabel->setAlignment( 289 );

	countbar = new MyProgressBar( this, "User_1" );
	countbar->setGeometry( 450, 60, 110, 30 );

	timelabel = new QLabel( this, "Label_14" );
	timelabel->setGeometry( 450, 100, 100, 20 );
	timelabel->setFrameStyle( 0 );
	timelabel->setText( i18n( "Time" ));
	timelabel->setAlignment( 289 );

	timebar = new MyProgressBar( this, "User_2" );
	timebar->setGeometry( 450, 120, 110, 30 );

	QLabel* qtarch_Label_9;
	qtarch_Label_9 = new QLabel( this, "Label_9" );
	qtarch_Label_9->setGeometry( 450, 160, 60, 20 );
	qtarch_Label_9->setFrameStyle( 0 );
	qtarch_Label_9->setText( i18n( "Cycle:" ));
	qtarch_Label_9->setAlignment( 289 );

	progCount = new QLabel( this, "Label_10" );
	progCount->setGeometry( 530, 160, 20, 20 );
	progCount->setFrameStyle( 0 );
	progCount->setText( i18n( "1" ));
	progCount->setAlignment( 289 );

	orgField = new QLabel( this, "Label_22" );
	orgField->setGeometry( 50, 60, 360, 30 );
	orgField->setFrameStyle( 51 );
	orgField->setText( "" );
	orgField->setAlignment( 289 );




	resize( 600,410 );
}


//ArtQueryDlgData::~ArtQueryDlgData()
//{
//}
#include "ArtQueryDlgData.moc"
