/**********************************************************************

	--- Qt Architect generated file ---

	File: MCQueryDlgData.cpp
	Last generated: Thu Oct 4 17:22:04 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "MCQueryDlgData.h"

#define Inherited QueryDlgBase

#include <qlabel.h>
#include <qbuttongroup.h>
#include <kapp.h>  // i18n macro

#include <compat_2x.h> // string type macro 


MCQueryDlgData::MCQueryDlgData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	QButtonGroup* qtarch_ButtonGroup_1;
	qtarch_ButtonGroup_1 = new QButtonGroup( this, "ButtonGroup_1" );
	qtarch_ButtonGroup_1->setGeometry( 10, 10, 580, 390 );
	qtarch_ButtonGroup_1->setFrameStyle( 49 );
	qtarch_ButtonGroup_1->setTitle( "" );
	qtarch_ButtonGroup_1->setAlignment( 1 );

	QButtonGroup* qtarch_ButtonGroup_4;
	qtarch_ButtonGroup_4 = new QButtonGroup( this, "ButtonGroup_4" );
	qtarch_ButtonGroup_4->setGeometry( 30, 20, 400, 160 );
	qtarch_ButtonGroup_4->setFrameStyle( 49 );
	qtarch_ButtonGroup_4->setTitle( i18n( "Original" ));
	qtarch_ButtonGroup_4->setAlignment( 1 );

	transgroup = new QButtonGroup( this, "ButtonGroup_2" );
	transgroup->setGeometry( 30, 200, 400, 180 );
	transgroup->setFrameStyle( 49 );
	transgroup->setTitle( i18n( "Translation" ));
	transgroup->setAlignment( 1 );

	b_edit = new QPushButton( this, "PushButton_6" );
	b_edit->setGeometry( 320, 120, 90, 30 );
	b_edit->setText( i18n( "&Edit" ));

	QLabel* qtarch_Label_3;
	qtarch_Label_3 = new QLabel( this, "Label_3" );
	qtarch_Label_3->setGeometry( 50, 100, 100, 20 );
	qtarch_Label_3->setFrameStyle( 0 );
	qtarch_Label_3->setText( i18n( "False friend:" ));
	qtarch_Label_3->setAlignment( 289 );

	QLabel* qtarch_Label_4;
	qtarch_Label_4 = new QLabel( this, "Label_4" );
	qtarch_Label_4->setGeometry( 50, 120, 100, 20 );
	qtarch_Label_4->setFrameStyle( 0 );
	qtarch_Label_4->setText( i18n( "Remark:" ));
	qtarch_Label_4->setAlignment( 289 );

	rb_trans1 = new QRadioButton( this, "RadioButton_1" );
	rb_trans1->setGeometry( 50, 230, 30, 20 );
	rb_trans1->setText( i18n( "&1:" ));
	rb_trans1->setChecked( FALSE );

	rb_trans2 = new QRadioButton( this, "RadioButton_2" );
	rb_trans2->setGeometry( 50, 260, 30, 20 );
	rb_trans2->setText( i18n( "&2:" ));
	rb_trans2->setChecked( FALSE );

	rb_trans3 = new QRadioButton( this, "RadioButton_3" );
	rb_trans3->setGeometry( 50, 290, 30, 20 );
	rb_trans3->setText( i18n( "&3:" ));
	rb_trans3->setChecked( FALSE );

	rb_trans4 = new QRadioButton( this, "RadioButton_4" );
	rb_trans4->setGeometry( 50, 320, 30, 20 );
	rb_trans4->setText( i18n( "&4:" ));
	rb_trans4->setChecked( FALSE );

	rb_trans5 = new QRadioButton( this, "RadioButton_5" );
	rb_trans5->setGeometry( 50, 350, 30, 20 );
	rb_trans5->setText( i18n( "&5:" ));
	rb_trans5->setChecked( FALSE );

	show_it = new QPushButton( this, "PushButton_2" );
	show_it->setGeometry( 300, 230, 110, 30 );
	show_it->setText( i18n( "Show &it" ));

	know_it = new QPushButton( this, "PushButton_5" );
	know_it->setGeometry( 300, 280, 110, 30 );
	know_it->setText( i18n( "I &know it" ));

	dont_know = new QPushButton( this, "PushButton_9" );
	dont_know->setGeometry( 300, 330, 110, 30 );
	dont_know->setText( i18n( "&Don't know" ));

	stop_it = new QPushButton( this, "PushButton_7" );
	stop_it->setGeometry( 460, 280, 100, 30 );
	stop_it->setText( i18n( "&Stop query" ));

	options = new QPushButton( this, "PushButton_8" );
	options->setGeometry( 460, 330, 100, 30 );
	options->setText( i18n( "&Options" ));

	falseFriend = new QLabel( this, "Label_5" );
	falseFriend->setGeometry( 160, 100, 150, 20 );
	falseFriend->setFrameStyle( 0 );
	falseFriend->setText( i18n( "false friend" ));
	falseFriend->setAlignment( 289 );

	remark = new QLabel( this, "Label_6" );
	remark->setGeometry( 160, 120, 150, 20 );
	remark->setFrameStyle( 0 );
	remark->setText( i18n( "remark" ));
	remark->setAlignment( 289 );

	QLabel* qtarch_Label_7;
	qtarch_Label_7 = new QLabel( this, "Label_7" );
	qtarch_Label_7->setGeometry( 50, 140, 100, 20 );
	qtarch_Label_7->setFrameStyle( 0 );
	qtarch_Label_7->setText( i18n( "Type:" ));
	qtarch_Label_7->setAlignment( 289 );

	type = new QLabel( this, "Label_8" );
	type->setGeometry( 160, 140, 150, 20 );
	type->setFrameStyle( 0 );
	type->setText( i18n( "type" ));
	type->setAlignment( 289 );

	QButtonGroup* qtarch_ButtonGroup_5;
	qtarch_ButtonGroup_5 = new QButtonGroup( this, "ButtonGroup_5" );
	qtarch_ButtonGroup_5->setGeometry( 440, 20, 130, 170 );
	qtarch_ButtonGroup_5->setFrameStyle( 49 );
	qtarch_ButtonGroup_5->setTitle( i18n( "Progress" ));
	qtarch_ButtonGroup_5->setAlignment( 1 );

	countlabel = new QLabel( this, "Label_13" );
	countlabel->setGeometry( 450, 40, 100, 20 );
	countlabel->setFrameStyle( 0 );
	countlabel->setText( i18n( "Count" ));
	countlabel->setAlignment( 289 );

	countbar = new MyProgressBar( this, "User_1" );
	countbar->setGeometry( 450, 60, 110, 30 );

	timelabel = new QLabel( this, "Label_14" );
	timelabel->setGeometry( 450, 100, 100, 20 );
	timelabel->setFrameStyle( 0 );
	timelabel->setText( i18n( "Time" ));
	timelabel->setAlignment( 289 );

	timebar = new MyProgressBar( this, "User_2" );
	timebar->setGeometry( 450, 120, 110, 30 );

	QLabel* qtarch_Label_9;
	qtarch_Label_9 = new QLabel( this, "Label_9" );
	qtarch_Label_9->setGeometry( 450, 160, 60, 20 );
	qtarch_Label_9->setFrameStyle( 0 );
	qtarch_Label_9->setText( i18n( "Cycle:" ));
	qtarch_Label_9->setAlignment( 289 );

	progCount = new QLabel( this, "Label_10" );
	progCount->setGeometry( 530, 160, 20, 20 );
	progCount->setFrameStyle( 0 );
	progCount->setText( i18n( "1" ));
	progCount->setAlignment( 289 );

	orgField = new QLabel( this, "Label_17" );
	orgField->setGeometry( 50, 60, 360, 30 );
	orgField->setFrameStyle( 51 );
	orgField->setText( "" );
	orgField->setAlignment( 289 );

	trans1 = new QLabel( this, "Label_18" );
	trans1->setGeometry( 90, 230, 200, 20 );
	trans1->setFrameStyle( 0 );
	trans1->setText( i18n( "-" ));
	trans1->setAlignment( 289 );

	trans2 = new QLabel( this, "Label_19" );
	trans2->setGeometry( 90, 260, 200, 20 );
	trans2->setFrameStyle( 0 );
	trans2->setText( i18n( "-" ));
	trans2->setAlignment( 289 );

	trans3 = new QLabel( this, "Label_20" );
	trans3->setGeometry( 90, 290, 200, 20 );
	trans3->setFrameStyle( 0 );
	trans3->setText( i18n( "-" ));
	trans3->setAlignment( 289 );

	trans4 = new QLabel( this, "Label_21" );
	trans4->setGeometry( 90, 320, 200, 20 );
	trans4->setFrameStyle( 0 );
	trans4->setText( i18n( "-" ));
	trans4->setAlignment( 289 );

	trans5 = new QLabel( this, "Label_22" );
	trans5->setGeometry( 90, 350, 200, 20 );
	trans5->setFrameStyle( 0 );
	trans5->setText( i18n( "-" ));
	trans5->setAlignment( 289 );





	resize( 600,410 );
}


//MCQueryDlgData::~MCQueryDlgData()
//{
//}
