/**********************************************************************

	--- Qt Architect generated file ---

	File: MCQueryDlgData.h
	Last generated: Thu Oct 4 17:22:04 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef MCQueryDlgData_included
#define MCQueryDlgData_included

#include <compat_2x.h> // string type macro 

#ifdef EA_KDE2x
#define EA_SPINBOX_H <qspinbox.h>
#define EA_SPINBOX   QSpinBox
#else
#define EA_SPINBOX_H <kspinbox.h>
#define EA_SPINBOX   KSpinBox
#endif
#include "QueryDlgBase.h"
#include <qlabel.h>
#include <qradiobutton.h>
#include <qpushbutton.h>
#include "MyProgress.h"
#include <qbuttongroup.h>

class MCQueryDlgData : public QueryDlgBase
{
    Q_OBJECT

public:

    MCQueryDlgData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

//  virtual ~MCQueryDlgData();

public slots:


protected slots:


protected:
    QButtonGroup* transgroup;
    QPushButton* b_edit;
    QRadioButton* rb_trans1;
    QRadioButton* rb_trans2;
    QRadioButton* rb_trans3;
    QRadioButton* rb_trans4;
    QRadioButton* rb_trans5;
    QPushButton* show_it;
    QPushButton* know_it;
    QPushButton* dont_know;
    QPushButton* stop_it;
    QPushButton* options;
    QLabel* falseFriend;
    QLabel* remark;
    QLabel* type;
    QLabel* countlabel;
    MyProgressBar* countbar;
    QLabel* timelabel;
    MyProgressBar* timebar;
    QLabel* progCount;
    QLabel* orgField;
    QLabel* trans1;
    QLabel* trans2;
    QLabel* trans3;
    QLabel* trans4;
    QLabel* trans5;

};

#endif // MCQueryDlgData_included
