/**********************************************************************

	--- Qt Architect generated file ---

	File: QueryDlgData.cpp
	Last generated: Sat Oct 13 15:52:52 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "QueryDlgData.h"

#define Inherited QueryDlgBase

#include <qlabel.h>
#include <qbuttongroup.h>
#include <kapp.h>  // i18n macro

#include <compat_2x.h> // string type macro 


QueryDlgData::QueryDlgData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	QButtonGroup* qtarch_ButtonGroup_1;
	qtarch_ButtonGroup_1 = new QButtonGroup( this, "ButtonGroup_1" );
	qtarch_ButtonGroup_1->setGeometry( 10, 10, 580, 390 );
	qtarch_ButtonGroup_1->setFrameStyle( 49 );
	qtarch_ButtonGroup_1->setTitle( "" );
	qtarch_ButtonGroup_1->setAlignment( 1 );

	QButtonGroup* qtarch_ButtonGroup_4;
	qtarch_ButtonGroup_4 = new QButtonGroup( this, "ButtonGroup_4" );
	qtarch_ButtonGroup_4->setGeometry( 30, 20, 400, 160 );
	qtarch_ButtonGroup_4->setFrameStyle( 49 );
	qtarch_ButtonGroup_4->setTitle( i18n( "Original" ));
	qtarch_ButtonGroup_4->setAlignment( 1 );

	QButtonGroup* qtarch_ButtonGroup_2;
	qtarch_ButtonGroup_2 = new QButtonGroup( this, "ButtonGroup_2" );
	qtarch_ButtonGroup_2->setGeometry( 30, 200, 400, 180 );
	qtarch_ButtonGroup_2->setFrameStyle( 49 );
	qtarch_ButtonGroup_2->setTitle( i18n( "Translation" ));
	qtarch_ButtonGroup_2->setAlignment( 1 );

	b_editorg = new QPushButton( this, "PushButton_6" );
	b_editorg->setGeometry( 360, 130, 60, 30 );
	b_editorg->setText( i18n( "&Edit" ));

	transField = new QLineEdit( this, "LineEdit_2" );
	transField->setGeometry( 40, 230, 310, 30 );
	transField->setText( "" );
	transField->setMaxLength( 32767 );

	show_more = new QPushButton( this, "PushButton_1" );
	show_more->setGeometry( 40, 280, 110, 30 );
	show_more->setText( i18n( "Show &more" ));

	show_all = new QPushButton( this, "PushButton_2" );
	show_all->setGeometry( 40, 330, 110, 30 );
	show_all->setText( i18n( "Show &all" ));

	verify = new QPushButton( this, "PushButton_3" );
	verify->setGeometry( 170, 280, 120, 30 );
	verify->setText( i18n( "&Verify" ));

	know_it = new QPushButton( this, "PushButton_5" );
	know_it->setGeometry( 310, 280, 110, 30 );
	know_it->setText( i18n( "I &know it" ));

	dont_know = new QPushButton( this, "PushButton_4" );
	dont_know->setGeometry( 310, 330, 110, 30 );
	dont_know->setText( i18n( "&Don't know" ));

	stop_it = new QPushButton( this, "PushButton_7" );
	stop_it->setGeometry( 460, 280, 100, 30 );
	stop_it->setText( i18n( "&Stop query" ));

	options = new QPushButton( this, "PushButton_8" );
	options->setGeometry( 460, 330, 100, 30 );
	options->setText( i18n( "&Options" ));

	falseFriend = new QLabel( this, "Label_5" );
	falseFriend->setGeometry( 160, 50, 250, 20 );
	falseFriend->setFrameStyle( 0 );
	falseFriend->setText( i18n( "false friend" ));
	falseFriend->setAlignment( 289 );

	remark = new QLabel( this, "Label_6" );
	remark->setGeometry( 160, 70, 250, 20 );
	remark->setFrameStyle( 0 );
	remark->setText( i18n( "remark" ));
	remark->setAlignment( 289 );

	type = new QLabel( this, "Label_8" );
	type->setGeometry( 160, 90, 250, 20 );
	type->setFrameStyle( 0 );
	type->setText( i18n( "type" ));
	type->setAlignment( 289 );

	b_edittrans = new QPushButton( this, "PushButton_14" );
	b_edittrans->setGeometry( 360, 230, 60, 30 );
	b_edittrans->setText( i18n( "E&dit" ));

	c_falsefriend = new QCheckBox( this, "CheckBox_1" );
	c_falsefriend->setGeometry( 40, 50, 110, 20 );
	c_falsefriend->setText( i18n( "&False friend:" ));
	c_falsefriend->setChecked( FALSE );

	c_remark = new QCheckBox( this, "CheckBox_2" );
	c_remark->setGeometry( 40, 70, 110, 20 );
	c_remark->setText( i18n( "&Remark:" ));
	c_remark->setChecked( FALSE );

	c_type = new QCheckBox( this, "CheckBox_3" );
	c_type->setGeometry( 40, 90, 110, 20 );
	c_type->setText( i18n( "T&ype:" ));
	c_type->setChecked( FALSE );

	QButtonGroup* qtarch_ButtonGroup_5;
	qtarch_ButtonGroup_5 = new QButtonGroup( this, "ButtonGroup_5" );
	qtarch_ButtonGroup_5->setGeometry( 440, 20, 130, 170 );
	qtarch_ButtonGroup_5->setFrameStyle( 49 );
	qtarch_ButtonGroup_5->setTitle( i18n( "Progress" ));
	qtarch_ButtonGroup_5->setAlignment( 1 );

	countlabel = new QLabel( this, "Label_13" );
	countlabel->setGeometry( 450, 40, 100, 20 );
	countlabel->setFrameStyle( 0 );
	countlabel->setText( i18n( "Count" ));
	countlabel->setAlignment( 289 );

	countbar = new MyProgressBar( this, "User_1" );
	countbar->setGeometry( 450, 60, 110, 30 );

	timelabel = new QLabel( this, "Label_14" );
	timelabel->setGeometry( 450, 100, 100, 20 );
	timelabel->setFrameStyle( 0 );
	timelabel->setText( i18n( "Time" ));
	timelabel->setAlignment( 289 );

	timebar = new MyProgressBar( this, "User_2" );
	timebar->setGeometry( 450, 120, 110, 30 );

	QLabel* qtarch_Label_9;
	qtarch_Label_9 = new QLabel( this, "Label_9" );
	qtarch_Label_9->setGeometry( 450, 160, 60, 20 );
	qtarch_Label_9->setFrameStyle( 0 );
	qtarch_Label_9->setText( i18n( "Cycle:" ));
	qtarch_Label_9->setAlignment( 289 );

	progCount = new QLabel( this, "Label_10" );
	progCount->setGeometry( 530, 160, 20, 20 );
	progCount->setFrameStyle( 0 );
	progCount->setText( i18n( "1" ));
	progCount->setAlignment( 289 );

	orgField = new QLabel( this, "Label_17" );
	orgField->setGeometry( 40, 130, 310, 30 );
	orgField->setFrameStyle( 51 );
	orgField->setText( "" );
	orgField->setAlignment( 289 );





	resize( 600,410 );
}


//QueryDlgData::~QueryDlgData()
//{
//}
#include "QueryDlgData.moc"
