/**********************************************************************

	--- Qt Architect generated file ---

	File: QueryDlgData.h
	Last generated: Sat Oct 13 15:52:52 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef QueryDlgData_included
#define QueryDlgData_included

#include <compat_2x.h> // string type macro 

#ifdef EA_KDE2x
#define EA_SPINBOX_H <qspinbox.h>
#define EA_SPINBOX   QSpinBox
#else
#define EA_SPINBOX_H <kspinbox.h>
#define EA_SPINBOX   KSpinBox
#endif
#include "QueryDlgBase.h"
#include <qlabel.h>
#include <qcheckbox.h>
#include <qpushbutton.h>
#include <qlineedit.h>
#include "MyProgress.h"

class QueryDlgData : public QueryDlgBase
{
    Q_OBJECT

public:

    QueryDlgData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

//  virtual ~QueryDlgData();

public slots:


protected slots:


protected:
    QPushButton* b_editorg;
    QLineEdit* transField;
    QPushButton* show_more;
    QPushButton* show_all;
    QPushButton* verify;
    QPushButton* know_it;
    QPushButton* dont_know;
    QPushButton* stop_it;
    QPushButton* options;
    QLabel* falseFriend;
    QLabel* remark;
    QLabel* type;
    QPushButton* b_edittrans;
    QCheckBox* c_falsefriend;
    QCheckBox* c_remark;
    QCheckBox* c_type;
    QLabel* countlabel;
    MyProgressBar* countbar;
    QLabel* timelabel;
    MyProgressBar* timebar;
    QLabel* progCount;
    QLabel* orgField;

};

#endif // QueryDlgData_included
