/**********************************************************************

	--- Qt Architect generated file ---

	File: GenOptPageData.h
	Last generated: Sat Oct 13 18:44:33 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef GenOptPageData_included
#define GenOptPageData_included

#include <compat_2x.h> // string type macro 

#ifdef EA_KDE2x
#define EA_SPINBOX_H <qspinbox.h>
#define EA_SPINBOX   QSpinBox
#else
#define EA_SPINBOX_H <kspinbox.h>
#define EA_SPINBOX   KSpinBox
#endif
#include <qdialog.h>
#include <qlabel.h>
#include <qradiobutton.h>
#include <qcheckbox.h>
#include <qlineedit.h>
#include <qbuttongroup.h>

class GenOptPageData : public QDialog
{
    Q_OBJECT

public:

    GenOptPageData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

//  virtual ~GenOptPageData();

public slots:


protected slots:


protected:
    QButtonGroup* group_resize;
    QLabel* label_btime;
    QLineEdit* e_btime;
    QRadioButton* hb_auto;
    QRadioButton* hb_percent;
    QRadioButton* hb_fixed;
    QCheckBox* c_smart;
    QCheckBox* c_saveopt;

};

#endif // GenOptPageData_included
