/**********************************************************************

	--- Qt Architect generated file ---

	File: LangOptPageData.cpp
	Last generated: Sat Oct 13 18:44:35 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "LangOptPageData.h"

#define Inherited QDialog

#include <qbuttongroup.h>
#include <kapp.h>  // i18n macro

#include <compat_2x.h> // string type macro 


LangOptPageData::LangOptPageData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	QButtonGroup* qtarch_ButtonGroup_11;
	qtarch_ButtonGroup_11 = new QButtonGroup( this, "ButtonGroup_11" );
	qtarch_ButtonGroup_11->setGeometry( 10, 10, 500, 340 );
	qtarch_ButtonGroup_11->setFrameStyle( 49 );
	qtarch_ButtonGroup_11->setTitle( i18n( "Available languages" ));
	qtarch_ButtonGroup_11->setAlignment( 1 );

	QButtonGroup* qtarch_ButtonGroup_19;
	qtarch_ButtonGroup_19 = new QButtonGroup( this, "ButtonGroup_19" );
	qtarch_ButtonGroup_19->setGeometry( 30, 30, 280, 210 );
	qtarch_ButtonGroup_19->setFrameStyle( 49 );
	qtarch_ButtonGroup_19->setTitle( "" );
	qtarch_ButtonGroup_19->setAlignment( 1 );

	lang_group = new QButtonGroup( this, "ButtonGroup_18" );
	lang_group->setGeometry( 30, 250, 460, 80 );
	lang_group->setFrameStyle( 49 );
	lang_group->setTitle( i18n( "Font for this language" ));
	lang_group->setAlignment( 1 );

	label_shortName = new QLabel( this, "Label_2" );
	label_shortName->setGeometry( 50, 40, 130, 20 );
	label_shortName->setFrameStyle( 0 );
	label_shortName->setText( i18n( "Language c&ode" ));
	label_shortName->setAlignment( 289 );

	d_shortName = new QComboBox( FALSE, this, "ComboBox_2" );
	d_shortName->setGeometry( 50, 60, 110, 30 );
	d_shortName->setSizeLimit( 10 );
	d_shortName->setAutoResize( FALSE );
	d_shortName->setMaxCount( 2147483647 );
	d_shortName->setAutoCompletion( FALSE );

	label_shortName2 = new QLabel( this, "Label_6" );
	label_shortName2->setGeometry( 180, 40, 110, 20 );
	label_shortName2->setFrameStyle( 0 );
	label_shortName2->setText( i18n( "Alte&rnative" ));
	label_shortName2->setAlignment( 289 );

	e_shortName2 = new QLineEdit( this, "LineEdit_6" );
	e_shortName2->setGeometry( 180, 60, 110, 30 );
	e_shortName2->setText( "" );
	e_shortName2->setMaxLength( 32767 );

	label_langLong = new QLabel( this, "Label_4" );
	label_langLong->setGeometry( 50, 100, 100, 20 );
	label_langLong->setFrameStyle( 0 );
	label_langLong->setText( i18n( "Lang&uage" ));
	label_langLong->setAlignment( 289 );

	e_langLong = new QLineEdit( this, "LineEdit_5" );
	e_langLong->setGeometry( 50, 120, 110, 30 );
	e_langLong->setText( "" );
	e_langLong->setMaxLength( 32767 );

	label_langPixmap = new QLabel( this, "Label_5" );
	label_langPixmap->setGeometry( 50, 170, 110, 20 );
	label_langPixmap->setFrameStyle( 0 );
	label_langPixmap->setText( i18n( "&Picture in header" ));
	label_langPixmap->setAlignment( 289 );

	b_langPixmap = new QPushButton( this, "PushButton_6" );
	b_langPixmap->setGeometry( 50, 190, 110, 30 );
	b_langPixmap->setText( i18n( "&Picture in header" ));

	b_langNew = new QPushButton( this, "PushButton_5" );
	b_langNew->setGeometry( 360, 100, 110, 30 );
	b_langNew->setText( i18n( "&New" ));

	b_langDel = new QPushButton( this, "PushButton_8" );
	b_langDel->setGeometry( 360, 170, 110, 30 );
	b_langDel->setText( i18n( "&Delete" ));

	e_font = new QLabel( this, "Label_7" );
	e_font->setGeometry( 280, 280, 190, 30 );
	e_font->setFrameStyle( 51 );
	e_font->setText( i18n( "?????" ));
	e_font->setAlignment( 289 );

	b_chooseFont = new QPushButton( this, "PushButton_1" );
	b_chooseFont->setGeometry( 170, 280, 100, 30 );
	b_chooseFont->setText( i18n( "C&hange" ));

	r_stand = new QRadioButton( this, "RadioButton_1" );
	r_stand->setGeometry( 50, 270, 110, 20 );
	r_stand->setText( i18n( "s&tandard" ));
	r_stand->setChecked( FALSE );

	r_spec = new QRadioButton( this, "RadioButton_2" );
	r_spec->setGeometry( 50, 300, 110, 20 );
	r_spec->setText( i18n( "spe&cial" ));
	r_spec->setChecked( FALSE );

	e_newName = new QLineEdit( this, "LineEdit_8" );
	e_newName->setGeometry( 360, 60, 110, 30 );
	e_newName->setText( "" );
	e_newName->setMaxLength( 32767 );

	label_newName = new QLabel( this, "Label_10" );
	label_newName->setGeometry( 360, 40, 100, 20 );
	label_newName->setFrameStyle( 0 );
	label_newName->setText( i18n( "N&ame" ));
	label_newName->setAlignment( 289 );




	resize( 520,360 );
}


//LangOptPageData::~LangOptPageData()
//{
//}
#include "LangOptPageData.moc"
