/**********************************************************************

	--- Qt Architect generated file ---

	File: LangOptPageData.h
	Last generated: Sat Oct 13 18:44:35 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef LangOptPageData_included
#define LangOptPageData_included

#include <compat_2x.h> // string type macro 

#ifdef EA_KDE2x
#define EA_SPINBOX_H <qspinbox.h>
#define EA_SPINBOX   QSpinBox
#else
#define EA_SPINBOX_H <kspinbox.h>
#define EA_SPINBOX   KSpinBox
#endif
#include <qdialog.h>
#include <qlabel.h>
#include <qradiobutton.h>
#include <qpushbutton.h>
#include <qcombobox.h>
#include <qlineedit.h>
#include <qbuttongroup.h>

class LangOptPageData : public QDialog
{
    Q_OBJECT

public:

    LangOptPageData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

//  virtual ~LangOptPageData();

public slots:


protected slots:


protected:
    QButtonGroup* lang_group;
    QLabel* label_shortName;
    QComboBox* d_shortName;
    QLabel* label_shortName2;
    QLineEdit* e_shortName2;
    QLabel* label_langLong;
    QLineEdit* e_langLong;
    QLabel* label_langPixmap;
    QPushButton* b_langPixmap;
    QPushButton* b_langNew;
    QPushButton* b_langDel;
    QLabel* e_font;
    QPushButton* b_chooseFont;
    QRadioButton* r_stand;
    QRadioButton* r_spec;
    QLineEdit* e_newName;
    QLabel* label_newName;

};

#endif // LangOptPageData_included
