/**********************************************************************

	--- Qt Architect generated file ---

	File: PasteOptPageData.cpp
	Last generated: Thu Oct 4 17:24:24 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "PasteOptPageData.h"

#define Inherited QDialog

#include <qbuttongroup.h>
#include <kapp.h>  // i18n macro

#include <compat_2x.h> // string type macro 


PasteOptPageData::PasteOptPageData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	QButtonGroup* qtarch_ButtonGroup_12;
	qtarch_ButtonGroup_12 = new QButtonGroup( this, "ButtonGroup_12" );
	qtarch_ButtonGroup_12->setGeometry( 10, 10, 500, 340 );
	qtarch_ButtonGroup_12->setFrameStyle( 49 );
	qtarch_ButtonGroup_12->setTitle( i18n( "Paste and copy options" ));
	qtarch_ButtonGroup_12->setAlignment( 1 );

	label_sep = new QLabel( this, "Label_3" );
	label_sep->setGeometry( 30, 40, 160, 20 );
	label_sep->setFrameStyle( 0 );
	label_sep->setText( i18n( "&Separator" ));
	label_sep->setAlignment( 289 );

	d_sep = new QComboBox( FALSE, this, "ComboBox_3" );
	d_sep->setGeometry( 30, 60, 170, 30 );
	d_sep->setSizeLimit( 10 );
	d_sep->setAutoResize( FALSE );
	d_sep->setMaxCount( 2147483647 );
	d_sep->setAutoCompletion( FALSE );

	label_order = new QLabel( this, "Label_7" );
	label_order->setGeometry( 30, 140, 160, 20 );
	label_order->setFrameStyle( 0 );
	label_order->setText( i18n( "&Order" ));
	label_order->setAlignment( 289 );

	order_list = new QListBox( this, "ListBox_1" );
	order_list->setGeometry( 30, 160, 170, 110 );
	order_list->setFrameStyle( 51 );
	order_list->setDragSelect( TRUE );
	order_list->setAutoScroll( TRUE );
	order_list->setScrollBar( FALSE );
	order_list->setAutoScrollBar( TRUE );
	order_list->setBottomScrollBar( FALSE );
	order_list->setAutoBottomScrollBar( TRUE );
	order_list->setSmoothScrolling( TRUE );
	order_list->setMultiSelection( FALSE );
	order_list->setAutoUpdate( TRUE );

	item_up = new QPushButton( this, "PushButton_2" );
	item_up->setGeometry( 220, 160, 100, 30 );
	item_up->setText( i18n( "&Up" ));

	item_skip = new QPushButton( this, "PushButton_1" );
	item_skip->setGeometry( 220, 200, 100, 30 );
	item_skip->setText( i18n( "S&kip" ));

	item_down = new QPushButton( this, "PushButton_3" );
	item_down->setGeometry( 220, 240, 100, 30 );
	item_down->setText( i18n( "&Down" ));

	item_curr_doc = new QCheckBox( this, "CheckBox_1" );
	item_curr_doc->setGeometry( 40, 280, 160, 30 );
	item_curr_doc->setText( i18n( "use cu&rrent document" ));
	item_curr_doc->setChecked( FALSE );


	resize( 520,360 );
}


//PasteOptPageData::~PasteOptPageData()
//{
//}
#include "PasteOptPageData.moc"
