/**********************************************************************

	--- Qt Architect generated file ---

	File: PasteOptPageData.h
	Last generated: Sat Oct 13 18:44:40 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef PasteOptPageData_included
#define PasteOptPageData_included

#include <compat_2x.h> // string type macro 

#ifdef EA_KDE2x
#define EA_SPINBOX_H <qspinbox.h>
#define EA_SPINBOX   QSpinBox
#else
#define EA_SPINBOX_H <kspinbox.h>
#define EA_SPINBOX   KSpinBox
#endif
#include <qdialog.h>
#include <qlabel.h>
#include <qcheckbox.h>
#include <qpushbutton.h>
#include <qcombobox.h>
#include <qlistbox.h>

class PasteOptPageData : public QDialog
{
    Q_OBJECT

public:

    PasteOptPageData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

//  virtual ~PasteOptPageData();

public slots:


protected slots:


protected:
    QLabel* label_sep;
    QComboBox* d_sep;
    QLabel* label_order;
    QListBox* order_list;
    QPushButton* item_up;
    QPushButton* item_skip;
    QPushButton* item_down;
    QCheckBox* item_curr_doc;

};

#endif // PasteOptPageData_included
