/**********************************************************************

	--- Qt Architect generated file ---

	File: ViewOptPageData.cpp
	Last generated: Sat Oct 13 18:44:38 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "ViewOptPageData.h"

#define Inherited QDialog

#include <qbuttongroup.h>
#include <kapp.h>  // i18n macro

#include <compat_2x.h> // string type macro 


ViewOptPageData::ViewOptPageData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	QButtonGroup* qtarch_ButtonGroup_12;
	qtarch_ButtonGroup_12 = new QButtonGroup( this, "ButtonGroup_12" );
	qtarch_ButtonGroup_12->setGeometry( 10, 10, 500, 340 );
	qtarch_ButtonGroup_12->setFrameStyle( 49 );
	qtarch_ButtonGroup_12->setTitle( i18n( "Viewing options" ));
	qtarch_ButtonGroup_12->setAlignment( 1 );

	gradegroup = new QButtonGroup( this, "ButtonGroup_13" );
	gradegroup->setGeometry( 270, 30, 220, 300 );
	gradegroup->setFrameStyle( 49 );
	gradegroup->setTitle( i18n( "Grade colors" ));
	gradegroup->setAlignment( 1 );

	QButtonGroup* qtarch_ButtonGroup_17;
	qtarch_ButtonGroup_17 = new QButtonGroup( this, "ButtonGroup_17" );
	qtarch_ButtonGroup_17->setGeometry( 30, 40, 220, 110 );
	qtarch_ButtonGroup_17->setFrameStyle( 49 );
	qtarch_ButtonGroup_17->setTitle( i18n( "Table font" ));
	qtarch_ButtonGroup_17->setAlignment( 1 );

	e_font = new QLabel( this, "Label_7" );
	e_font->setGeometry( 40, 110, 200, 30 );
	e_font->setFrameStyle( 51 );
	e_font->setText( i18n( "?????" ));
	e_font->setAlignment( 289 );

	b_choose = new QPushButton( this, "PushButton_1" );
	b_choose->setGeometry( 40, 70, 80, 30 );
	b_choose->setText( i18n( "C&hange" ));

	c_use = new QCheckBox( this, "CheckBox_1" );
	c_use->setGeometry( 290, 50, 130, 20 );
	c_use->setText( i18n( "&Use colors" ));
	c_use->setChecked( FALSE );

	l_lev7 = new QLabel( this, "Label_36" );
	l_lev7->setGeometry( 290, 80, 80, 20 );
	l_lev7->setFrameStyle( 0 );
	l_lev7->setText( i18n( "Level &7:" ));
	l_lev7->setAlignment( 289 );

	b_col7 = new KColorButton( this, "KColorButton_12" );
	b_col7->setGeometry( 430, 80, 40, 20 );
	b_col7->setText( i18n( "&7" ));
	b_col7->setColor( QColor( QRgb( 0 ) ) );

	l_lev6 = new QLabel( this, "Label_34" );
	l_lev6->setGeometry( 290, 110, 80, 20 );
	l_lev6->setFrameStyle( 0 );
	l_lev6->setText( i18n( "Level &6:" ));
	l_lev6->setAlignment( 289 );

	b_col6 = new KColorButton( this, "KColorButton_11" );
	b_col6->setGeometry( 430, 110, 40, 20 );
	b_col6->setText( i18n( "&6" ));
	b_col6->setColor( QColor( QRgb( 0 ) ) );

	l_lev5 = new QLabel( this, "Label_29" );
	l_lev5->setGeometry( 290, 140, 80, 20 );
	l_lev5->setFrameStyle( 0 );
	l_lev5->setText( i18n( "Level &5:" ));
	l_lev5->setAlignment( 289 );

	b_col5 = new KColorButton( this, "KColorButton_10" );
	b_col5->setGeometry( 430, 140, 40, 20 );
	b_col5->setText( i18n( "&5" ));
	b_col5->setColor( QColor( QRgb( 0 ) ) );

	l_lev4 = new QLabel( this, "Label_35" );
	l_lev4->setGeometry( 290, 170, 80, 20 );
	l_lev4->setFrameStyle( 0 );
	l_lev4->setText( i18n( "Level &4:" ));
	l_lev4->setAlignment( 289 );

	b_col4 = new KColorButton( this, "KColorButton_5" );
	b_col4->setGeometry( 430, 170, 40, 20 );
	b_col4->setText( i18n( "&4" ));
	b_col4->setColor( QColor( QRgb( 0 ) ) );

	l_lev3 = new QLabel( this, "Label_28" );
	l_lev3->setGeometry( 290, 200, 80, 20 );
	l_lev3->setFrameStyle( 0 );
	l_lev3->setText( i18n( "Level &3:" ));
	l_lev3->setAlignment( 289 );

	b_col3 = new KColorButton( this, "KColorButton_4" );
	b_col3->setGeometry( 430, 200, 40, 20 );
	b_col3->setText( i18n( "&3" ));
	b_col3->setColor( QColor( QRgb( 0 ) ) );

	l_lev2 = new QLabel( this, "Label_27" );
	l_lev2->setGeometry( 290, 230, 80, 20 );
	l_lev2->setFrameStyle( 0 );
	l_lev2->setText( i18n( "Level &2:" ));
	l_lev2->setAlignment( 289 );

	b_col2 = new KColorButton( this, "KColorButton_3" );
	b_col2->setGeometry( 430, 230, 40, 20 );
	b_col2->setText( i18n( "&2" ));
	b_col2->setColor( QColor( QRgb( 0 ) ) );

	l_lev1 = new QLabel( this, "Label_26" );
	l_lev1->setGeometry( 290, 260, 80, 20 );
	l_lev1->setFrameStyle( 0 );
	l_lev1->setText( i18n( "Level &1:" ));
	l_lev1->setAlignment( 289 );

	b_col1 = new KColorButton( this, "KColorButton_1" );
	b_col1->setGeometry( 430, 260, 40, 20 );
	b_col1->setText( i18n( "&1" ));
	b_col1->setColor( QColor( QRgb( 0 ) ) );

	l_lev0 = new QLabel( this, "Label_30" );
	l_lev0->setGeometry( 290, 290, 80, 20 );
	l_lev0->setFrameStyle( 0 );
	l_lev0->setText( i18n( "&Not queried:" ));
	l_lev0->setAlignment( 289 );

	b_col0 = new KColorButton( this, "KColorButton_9" );
	b_col0->setGeometry( 430, 290, 40, 20 );
	b_col0->setText( i18n( "&N" ));
	b_col0->setColor( QColor( QRgb( 0 ) ) );




	resize( 520,360 );
}


//ViewOptPageData::~ViewOptPageData()
//{
//}

#include "ViewOptPageData.moc"
