/**********************************************************************

	--- Qt Architect generated file ---

	File: CharSetDlgData.cpp
	Last generated: Thu Oct 4 17:20:39 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "CharSetDlgData.h"

#define Inherited QDialog

#include <kapp.h>  // i18n macro

#include <compat_2x.h> // string type macro 


CharSetDlgData::CharSetDlgData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	l_text = new QLabel( this, "Label_6" );
	l_text->setGeometry( 100, 30, 350, 100 );
	l_text->setFrameStyle( 0 );
	l_text->setText( "" );
	l_text->setAlignment( 289 );

	listbox = new QListBox( this, "ListBox_1" );
	listbox->setGeometry( 20, 170, 420, 110 );
	listbox->setFrameStyle( 51 );
	listbox->setDragSelect( TRUE );
	listbox->setAutoScroll( TRUE );
	listbox->setScrollBar( FALSE );
	listbox->setAutoScrollBar( TRUE );
	listbox->setBottomScrollBar( FALSE );
	listbox->setAutoBottomScrollBar( TRUE );
	listbox->setSmoothScrolling( TRUE );
	listbox->setMultiSelection( FALSE );
	listbox->setAutoUpdate( TRUE );

	b_ok = new QPushButton( this, "PushButton_1" );
	b_ok->setGeometry( 20, 360, 100, 30 );
	b_ok->setText( i18n( "&OK" ));

	b_cancel = new QPushButton( this, "PushButton_2" );
	b_cancel->setGeometry( 140, 360, 100, 30 );
	b_cancel->setText( i18n( "&Cancel" ));

	e_sample = new QLineEdit( this, "LineEdit_1" );
	e_sample->setGeometry( 20, 310, 420, 30 );
	e_sample->setText( "" );
	e_sample->setMaxLength( 32767 );

	l_sample = new QLabel( this, "Label_7" );
	l_sample->setGeometry( 20, 290, 260, 20 );
	l_sample->setFrameStyle( 0 );
	l_sample->setText( i18n( "&Sample text" ));
	l_sample->setAlignment( 289 );

	l_charset = new QLabel( this, "Label_8" );
	l_charset->setGeometry( 20, 150, 300, 20 );
	l_charset->setFrameStyle( 0 );
	l_charset->setText( i18n( "Available &fonts" ));
	l_charset->setAlignment( 289 );

	l_pixmap = new QLabel( this, "Label_9" );
	l_pixmap->setGeometry( 30, 30, 44, 44 );
	l_pixmap->setFrameStyle( 0 );
	l_pixmap->setText( "" );
	l_pixmap->setAlignment( 289 );

	resize( 470,410 );
}


//CharSetDlgData::~CharSetDlgData()
//{
//}
