/**********************************************************************

	--- Qt Architect generated file ---

	File: CharSetDlgData.h
	Last generated: Thu Oct 4 17:20:39 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef CharSetDlgData_included
#define CharSetDlgData_included

#include <compat_2x.h> // string type macro 

#ifdef EA_KDE2x
#define EA_SPINBOX_H <qspinbox.h>
#define EA_SPINBOX   QSpinBox
#else
#define EA_SPINBOX_H <kspinbox.h>
#define EA_SPINBOX   KSpinBox
#endif
#include <qdialog.h>
#include <qlabel.h>
#include <qpushbutton.h>
#include <qlistbox.h>
#include <qlineedit.h>

class CharSetDlgData : public QDialog
{
    Q_OBJECT

public:

    CharSetDlgData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

//  virtual ~CharSetDlgData();

public slots:


protected slots:


protected:
    QLabel* l_text;
    QListBox* listbox;
    QPushButton* b_ok;
    QPushButton* b_cancel;
    QLineEdit* e_sample;
    QLabel* l_sample;
    QLabel* l_charset;
    QLabel* l_pixmap;

};

#endif // CharSetDlgData_included
