/**********************************************************************

	--- Qt Architect generated file ---

	File: LessonInputDlgData.h
	Last generated: Thu Oct 4 17:20:29 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef LessonInputDlgData_included
#define LessonInputDlgData_included

#include <compat_2x.h> // string type macro 

#ifdef EA_KDE2x
#define EA_SPINBOX_H <qspinbox.h>
#define EA_SPINBOX   QSpinBox
#else
#define EA_SPINBOX_H <kspinbox.h>
#define EA_SPINBOX   KSpinBox
#endif
#include <qdialog.h>
#include <qlabel.h>
#include <qpushbutton.h>
#include <qlineedit.h>

class LessonInputDlgData : public QDialog
{
    Q_OBJECT

public:

    LessonInputDlgData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

//  virtual ~LessonInputDlgData();

public slots:


protected slots:


protected:
    QLineEdit* e_title;
    QLabel* title_label;
    QPushButton* b_ok;
    QPushButton* b_cancel;

};

#endif // LessonInputDlgData_included
