/**********************************************************************

	--- Qt Architect generated file ---

	File: NumLessonDlgData.cpp
	Last generated: Thu Oct 4 17:20:34 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "NumLessonDlgData.h"

#define Inherited QDialog

#include <kapp.h>  // i18n macro

#include <compat_2x.h> // string type macro 


NumLessonDlgData::NumLessonDlgData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	title_label = new QLabel( this, "Label_1" );
	title_label->setGeometry( 20, 20, 220, 20 );
	title_label->setFrameStyle( 0 );
	title_label->setText( i18n( "Number of entries per lesson" ));
	title_label->setAlignment( 289 );

	b_ok = new QPushButton( this, "PushButton_1" );
	b_ok->setGeometry( 20, 90, 100, 30 );
	b_ok->setText( i18n( "&OK" ));
	b_ok->setAutoDefault( TRUE );

	b_cancel = new QPushButton( this, "PushButton_2" );
	b_cancel->setGeometry( 150, 90, 100, 30 );
	b_cancel->setText( i18n( "&Cancel" ));

	e_title = new QLineEdit( this, "LineEdit_1" );
	e_title->setGeometry( 20, 40, 230, 30 );
	e_title->setText( "" );
	e_title->setMaxLength( 32767 );

	resize( 270,140 );
}


//NumLessonDlgData::~NumLessonDlgData()
//{
//}
