/**********************************************************************

	--- Qt Architect generated file ---

	File: NumLessonDlgData.h
	Last generated: Thu Oct 4 17:20:34 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef NumLessonDlgData_included
#define NumLessonDlgData_included

#include <compat_2x.h> // string type macro 

#ifdef EA_KDE2x
#define EA_SPINBOX_H <qspinbox.h>
#define EA_SPINBOX   QSpinBox
#else
#define EA_SPINBOX_H <kspinbox.h>
#define EA_SPINBOX   KSpinBox
#endif
#include <qdialog.h>
#include <qlabel.h>
#include <qpushbutton.h>
#include <qlineedit.h>

class NumLessonDlgData : public QDialog
{
    Q_OBJECT

public:

    NumLessonDlgData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

//  virtual ~NumLessonDlgData();

public slots:


protected slots:


protected:
    QLabel* title_label;
    QPushButton* b_ok;
    QPushButton* b_cancel;
    QLineEdit* e_title;

};

#endif // NumLessonDlgData_included
