/**********************************************************************

	--- Qt Architect generated file ---

	File: ProgressDlgData.h
	Last generated: Thu Oct 4 17:20:26 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef ProgressDlgData_included
#define ProgressDlgData_included

#include <compat_2x.h> // string type macro 

#ifdef EA_KDE2x
#define EA_SPINBOX_H <qspinbox.h>
#define EA_SPINBOX   QSpinBox
#else
#define EA_SPINBOX_H <kspinbox.h>
#define EA_SPINBOX   KSpinBox
#endif
#include "qsemimodal.h"
#include <qlabel.h>
#include <kprogress.h>

class ProgressDlgData : public QSemiModal
{
    Q_OBJECT

public:

    ProgressDlgData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

//  virtual ~ProgressDlgData();

public slots:


protected slots:


protected:
    KProgress* progress;
    QLabel* l_file;
    QLabel* l_title;

};

#endif // ProgressDlgData_included
