/**********************************************************************

	--- Qt Architect generated file ---

	File: ProgressDlgData.cpp
	Last generated: Thu Oct 4 17:20:26 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "ProgressDlgData.h"

#define Inherited QSemiModal

#include <qlabel.h>
#include <kapp.h>  // i18n macro

#include <compat_2x.h> // string type macro 


ProgressDlgData::ProgressDlgData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	progress = new KProgress( this, "KProgress_1" );
	progress->setGeometry( 30, 70, 340, 30 );
	{
		QFont font( "helvetica", 12, 75, 0 );
		font.setStyleHint( (QFont::StyleHint)5 );
		font.setCharSet( (QFont::CharSet)0 );
		progress->setFont( font );
	}
	progress->setFrameStyle( 51 );
	progress->setBarStyle( KProgress::Solid );
	progress->setOrientation( KProgress::Horizontal );
	progress->setBarColor( QColor( QRgb( 10236209 ) ) );
	progress->setTextEnabled( TRUE );
	progress->setValue( 0 );
	progress->setSteps( 1, 10 );
	progress->setRange( 0, 100 );

	QLabel* qtarch_Label_2;
	qtarch_Label_2 = new QLabel( this, "Label_2" );
	qtarch_Label_2->setGeometry( 30, 10, 90, 30 );
	{
		QFont font( "helvetica", 12, 75, 0 );
		font.setStyleHint( (QFont::StyleHint)0 );
		font.setCharSet( (QFont::CharSet)0 );
		qtarch_Label_2->setFont( font );
	}
	qtarch_Label_2->setFrameStyle( 0 );
	qtarch_Label_2->setText( i18n( "Filename:" ));
	qtarch_Label_2->setAlignment( 289 );

	l_file = new QLabel( this, "Label_3" );
	l_file->setGeometry( 130, 20, 250, 20 );
	l_file->setFrameStyle( 0 );
	l_file->setText( i18n( "file.kvtml" ));
	l_file->setAlignment( 265 );

	QLabel* qtarch_Label_4;
	qtarch_Label_4 = new QLabel( this, "Label_4" );
	qtarch_Label_4->setGeometry( 30, 30, 90, 30 );
	{
		QFont font( "helvetica", 12, 75, 0 );
		font.setStyleHint( (QFont::StyleHint)0 );
		font.setCharSet( (QFont::CharSet)0 );
		qtarch_Label_4->setFont( font );
	}
	qtarch_Label_4->setFrameStyle( 0 );
	qtarch_Label_4->setText( i18n( "Title:" ));
	qtarch_Label_4->setAlignment( 289 );

	l_title = new QLabel( this, "Label_5" );
	l_title->setGeometry( 130, 40, 250, 20 );
	l_title->setFrameStyle( 0 );
	l_title->setText( i18n( "Title" ));
	l_title->setAlignment( 265 );

	resize( 400,130 );
}


//ProgressDlgData::~ProgressDlgData()
//{
//}
