/**********************************************************************

	--- Qt Architect generated file ---

	File: AdjEntryPageData.cpp
	Last generated: Fri Oct 5 18:15:18 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "AdjEntryPageData.h"

#define Inherited QDialog

#include <qbuttongroup.h>
#include <kapp.h>  // i18n macro

#include <compat_2x.h> // string type macro 


AdjEntryPageData::AdjEntryPageData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	QButtonGroup* qtarch_ButtonGroup_15;
	qtarch_ButtonGroup_15 = new QButtonGroup( this, "ButtonGroup_15" );
	qtarch_ButtonGroup_15->setGeometry( 10, 10, 580, 390 );
	qtarch_ButtonGroup_15->setFrameStyle( 49 );
	qtarch_ButtonGroup_15->setTitle( i18n( "Conjugation of verbs" ));
	qtarch_ButtonGroup_15->setAlignment( 1 );

	lev1Label = new QLabel( this, "Label_11" );
	lev1Label->setGeometry( 60, 70, 100, 30 );
	lev1Label->setFrameStyle( 0 );
	lev1Label->setText( i18n( "Level &1" ));
	lev1Label->setAlignment( 289 );

	lev1Field = new QLineEdit( this, "LineEdit_3" );
	lev1Field->setGeometry( 170, 70, 330, 30 );
	lev1Field->setText( "" );
	lev1Field->setMaxLength( 32767 );

	lev2Label = new QLabel( this, "Label_12" );
	lev2Label->setGeometry( 60, 130, 100, 30 );
	lev2Label->setFrameStyle( 0 );
	lev2Label->setText( i18n( "Level &2" ));
	lev2Label->setAlignment( 289 );

	lev2Field = new QLineEdit( this, "LineEdit_4" );
	lev2Field->setGeometry( 170, 130, 330, 30 );
	lev2Field->setText( "" );
	lev2Field->setMaxLength( 32767 );

	lev3Label = new QLabel( this, "Label_13" );
	lev3Label->setGeometry( 60, 190, 100, 30 );
	lev3Label->setFrameStyle( 0 );
	lev3Label->setText( i18n( "Level &3" ));
	lev3Label->setAlignment( 289 );

	lev3Field = new QLineEdit( this, "LineEdit_5" );
	lev3Field->setGeometry( 170, 190, 330, 30 );
	lev3Field->setText( "" );
	lev3Field->setMaxLength( 32767 );


	resize( 600,410 );
}


//AdjEntryPageData::~AdjEntryPageData()
//{
//}
#include "AdjEntryPageData.moc"
