/**********************************************************************

	--- Qt Architect generated file ---

	File: AdjEntryPageData.h
	Last generated: Thu Oct 4 17:25:18 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef AdjEntryPageData_included
#define AdjEntryPageData_included

#include <compat_2x.h> // string type macro 

#ifdef EA_KDE2x
#define EA_SPINBOX_H <qspinbox.h>
#define EA_SPINBOX   QSpinBox
#else
#define EA_SPINBOX_H <kspinbox.h>
#define EA_SPINBOX   KSpinBox
#endif
#include <qdialog.h>
#include <qlabel.h>
#include <qlineedit.h>

class AdjEntryPageData : public QDialog
{
    Q_OBJECT

public:

    AdjEntryPageData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

//  virtual ~AdjEntryPageData();

public slots:


protected slots:


protected:
    QLabel* lev1Label;
    QLineEdit* lev1Field;
    QLabel* lev2Label;
    QLineEdit* lev2Field;
    QLabel* lev3Label;
    QLineEdit* lev3Field;

};

#endif // AdjEntryPageData_included
