/**********************************************************************

	--- Qt Architect generated file ---

	File: AuxInfoEntryPageData.cpp
	Last generated: Sat Oct 13 22:06:28 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "AuxInfoEntryPageData.h"

#define Inherited QDialog

#include <qbuttongroup.h>
#include <kapp.h>  // i18n macro

#include <compat_2x.h> // string type macro 


AuxInfoEntryPageData::AuxInfoEntryPageData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	QButtonGroup* qtarch_ButtonGroup_15;
	qtarch_ButtonGroup_15 = new QButtonGroup( this, "ButtonGroup_15" );
	qtarch_ButtonGroup_15->setGeometry( 10, 10, 580, 390 );
	qtarch_ButtonGroup_15->setFrameStyle( 49 );
	qtarch_ButtonGroup_15->setTitle( i18n( "Additional properties" ));
	qtarch_ButtonGroup_15->setAlignment( 1 );

	synonym_label = new QLabel( this, "Label_29" );
	synonym_label->setGeometry( 30, 40, 90, 20 );
	synonym_label->setFrameStyle( 0 );
	synonym_label->setText( i18n( "S&ynonyms:" ));
	synonym_label->setAlignment( 289 );

	antonym_label = new QLabel( this, "Label_37" );
	antonym_label->setGeometry( 30, 110, 90, 20 );
	antonym_label->setFrameStyle( 0 );
	antonym_label->setText( i18n( "Ant&onyms:" ));
	antonym_label->setAlignment( 289 );

	examp_label = new QLabel( this, "Label_28" );
	examp_label->setGeometry( 30, 180, 90, 20 );
	examp_label->setFrameStyle( 0 );
	examp_label->setText( i18n( "E&xample:" ));
	examp_label->setAlignment( 289 );

	remark_label = new QLabel( this, "Label_21" );
	remark_label->setGeometry( 30, 250, 90, 20 );
	remark_label->setFrameStyle( 0 );
	remark_label->setText( i18n( "&Remark:" ));
	remark_label->setAlignment( 289 );

	para_label = new QLabel( this, "Label_41" );
	para_label->setGeometry( 30, 320, 90, 20 );
	para_label->setFrameStyle( 0 );
	para_label->setText( i18n( "&Paraphrase:" ));
	para_label->setAlignment( 289 );

	synonym_line = new QMultiLineEdit( this, "MultiLineEdit_1" );
	synonym_line->setGeometry( 130, 40, 440, 50 );
	synonym_line->setFrameStyle( 51 );
	synonym_line->insertLine( "" );
	synonym_line->setReadOnly( FALSE );
	synonym_line->setOverwriteMode( FALSE );
	synonym_line->setAutoUpdate( TRUE );

	antonym_line = new QMultiLineEdit( this, "MultiLineEdit_2" );
	antonym_line->setGeometry( 130, 110, 440, 50 );
	antonym_line->setFrameStyle( 51 );
	antonym_line->insertLine( "" );
	antonym_line->setReadOnly( FALSE );
	antonym_line->setOverwriteMode( FALSE );
	antonym_line->setAutoUpdate( TRUE );

	examp_line = new QMultiLineEdit( this, "MultiLineEdit_3" );
	examp_line->setGeometry( 130, 180, 440, 50 );
	examp_line->setFrameStyle( 51 );
	examp_line->insertLine( "" );
	examp_line->setReadOnly( FALSE );
	examp_line->setOverwriteMode( FALSE );
	examp_line->setAutoUpdate( TRUE );

	remark_line = new QMultiLineEdit( this, "MultiLineEdit_4" );
	remark_line->setGeometry( 130, 250, 440, 50 );
	remark_line->setFrameStyle( 51 );
	remark_line->insertLine( "" );
	remark_line->setReadOnly( FALSE );
	remark_line->setOverwriteMode( FALSE );
	remark_line->setAutoUpdate( TRUE );

	para_line = new QMultiLineEdit( this, "MultiLineEdit_5" );
	para_line->setGeometry( 130, 320, 440, 50 );
	para_line->setFrameStyle( 51 );
	para_line->insertLine( "" );
	para_line->setReadOnly( FALSE );
	para_line->setOverwriteMode( FALSE );
	para_line->setAutoUpdate( TRUE );


	resize( 600,410 );
}


//AuxInfoEntryPageData::~AuxInfoEntryPageData()
//{
//}
#include "AuxInfoEntryPageData.moc"
