/**********************************************************************

	--- Qt Architect generated file ---

	File: CommonEntryPageData.cpp
	Last generated: Fri Oct 5 18:15:06 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "CommonEntryPageData.h"

#define Inherited QDialog

#include <qbuttongroup.h>
#include <kapp.h>  // i18n macro

#include <compat_2x.h> // string type macro 


CommonEntryPageData::CommonEntryPageData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	QButtonGroup* qtarch_ButtonGroup_15;
	qtarch_ButtonGroup_15 = new QButtonGroup( this, "ButtonGroup_15" );
	qtarch_ButtonGroup_15->setGeometry( 10, 10, 580, 390 );
	qtarch_ButtonGroup_15->setFrameStyle( 49 );
	qtarch_ButtonGroup_15->setTitle( i18n( "Common properties" ));
	qtarch_ButtonGroup_15->setAlignment( 1 );

	expr_label = new QLabel( this, "Expression" );
	expr_label->setGeometry( 30, 30, 260, 20 );
	expr_label->setFrameStyle( 0 );
	expr_label->setText( i18n( "&Expression" ));
	expr_label->setAlignment( 289 );

	expr_line = new QLineEdit( this, "LineEdit_1" );
	expr_line->setGeometry( 30, 50, 490, 30 );
	expr_line->setText( "" );
	expr_line->setMaxLength( 32767 );

	pronunce_label = new QLabel( this, "Label_23" );
	pronunce_label->setGeometry( 30, 90, 270, 20 );
	pronunce_label->setFrameStyle( 0 );
	pronunce_label->setText( i18n( "&Pronounciation" ));
	pronunce_label->setAlignment( 289 );

	pronunce_line = new QLineEdit( this, "LineEdit_3" );
	pronunce_line->setGeometry( 30, 110, 490, 30 );
	pronunce_line->setText( "" );
	pronunce_line->setMaxLength( 32767 );

	b_pronDlg = new QPushButton( this, "PushButton_1" );
	b_pronDlg->setGeometry( 540, 110, 30, 30 );
	b_pronDlg->setText( "" );

	type_label = new QLabel( this, "Label_22" );
	type_label->setGeometry( 30, 150, 140, 20 );
	type_label->setFrameStyle( 0 );
	type_label->setText( i18n( "T&ype" ));
	type_label->setAlignment( 289 );

	type_box = new QComboBox( FALSE, this, "ComboBox_4" );
	type_box->setGeometry( 30, 170, 290, 30 );
	type_box->setSizeLimit( 10 );
	type_box->setAutoResize( FALSE );
	type_box->setMaxCount( 2147483647 );
	type_box->setAutoCompletion( FALSE );

	subtype_label = new QLabel( this, "Label_24" );
	subtype_label->setGeometry( 330, 150, 160, 20 );
	subtype_label->setFrameStyle( 0 );
	subtype_label->setText( i18n( "&Subtype" ));
	subtype_label->setAlignment( 289 );

	subtype_box = new QComboBox( FALSE, this, "ComboBox_5" );
	subtype_box->setGeometry( 330, 170, 190, 30 );
	subtype_box->setSizeLimit( 10 );
	subtype_box->setAutoResize( FALSE );
	subtype_box->setMaxCount( 2147483647 );
	subtype_box->setAutoCompletion( FALSE );

	b_TypeDlg = new QPushButton( this, "PushButton_3" );
	b_TypeDlg->setGeometry( 540, 170, 30, 30 );
	b_TypeDlg->setText( "" );

	lesson_label = new QLabel( this, "Label_4" );
	lesson_label->setGeometry( 30, 310, 140, 20 );
	lesson_label->setFrameStyle( 0 );
	lesson_label->setText( i18n( "&Lesson" ));
	lesson_label->setAlignment( 289 );

	lesson_box = new QComboBox( FALSE, this, "ComboBox_3" );
	lesson_box->setGeometry( 30, 330, 490, 30 );
	lesson_box->setSizeLimit( 10 );
	lesson_box->setAutoResize( FALSE );
	lesson_box->setMaxCount( 2147483647 );
	lesson_box->setAutoCompletion( FALSE );

	b_LessDlg = new QPushButton( this, "PushButton_2" );
	b_LessDlg->setGeometry( 540, 330, 30, 30 );
	b_LessDlg->setText( "" );

	usage_label = new QLabel( this, "Label_39" );
	usage_label->setGeometry( 30, 210, 140, 20 );
	usage_label->setFrameStyle( 0 );
	usage_label->setText( i18n( "&Usage label" ));
	usage_label->setAlignment( 289 );

	b_usageDlg = new QPushButton( this, "PushButton_5" );
	b_usageDlg->setGeometry( 540, 230, 30, 30 );
	b_usageDlg->setText( "" );

	usage_box = new QListBox( this, "ListBox_1" );
	usage_box->setGeometry( 30, 230, 180, 70 );
	usage_box->setFrameStyle( 51 );
	usage_box->setDragSelect( TRUE );
	usage_box->setAutoScroll( TRUE );
	usage_box->setScrollBar( FALSE );
	usage_box->setAutoScrollBar( TRUE );
	usage_box->setBottomScrollBar( FALSE );
	usage_box->setAutoBottomScrollBar( TRUE );
	usage_box->setSmoothScrolling( TRUE );
	usage_box->setMultiSelection( TRUE );
	usage_box->setAutoUpdate( TRUE );

	usage_line = new QLabel( this, "Label_42" );
	usage_line->setGeometry( 220, 230, 300, 30 );
	usage_line->setFrameStyle( 51 );
	usage_line->setText( "" );
	usage_line->setAlignment( 289 );


	resize( 600,410 );
}


//CommonEntryPageData::~CommonEntryPageData()
//{
//}
