/**********************************************************************

	--- Qt Architect generated file ---

	File: CommonEntryPageData.h
	Last generated: Thu Oct 4 17:25:12 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef CommonEntryPageData_included
#define CommonEntryPageData_included

#include <compat_2x.h> // string type macro 

#ifdef EA_KDE2x
#define EA_SPINBOX_H <qspinbox.h>
#define EA_SPINBOX   QSpinBox
#else
#define EA_SPINBOX_H <kspinbox.h>
#define EA_SPINBOX   KSpinBox
#endif
#include <qdialog.h>
#include <qlabel.h>
#include <qpushbutton.h>
#include <qcombobox.h>
#include <qlistbox.h>
#include <qlineedit.h>

class CommonEntryPageData : public QDialog
{
    Q_OBJECT

public:

    CommonEntryPageData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

//  virtual ~CommonEntryPageData();

public slots:


protected slots:


protected:
    QLabel* expr_label;
    QLineEdit* expr_line;
    QLabel* pronunce_label;
    QLineEdit* pronunce_line;
    QPushButton* b_pronDlg;
    QLabel* type_label;
    QComboBox* type_box;
    QLabel* subtype_label;
    QComboBox* subtype_box;
    QPushButton* b_TypeDlg;
    QLabel* lesson_label;
    QComboBox* lesson_box;
    QPushButton* b_LessDlg;
    QLabel* usage_label;
    QPushButton* b_usageDlg;
    QListBox* usage_box;
    QLabel* usage_line;

};

#endif // CommonEntryPageData_included
