/**********************************************************************

	--- Qt Architect generated file ---

	File: FromToEntryPageData.h
	Last generated: Fri Oct 5 18:15:01 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef FromToEntryPageData_included
#define FromToEntryPageData_included

#include <compat_2x.h> // string type macro 

#ifdef EA_KDE2x
#define EA_SPINBOX_H <qspinbox.h>
#define EA_SPINBOX   QSpinBox
#else
#define EA_SPINBOX_H <kspinbox.h>
#define EA_SPINBOX   KSpinBox
#endif
#include <qdialog.h>
#include <qlabel.h>
#include <qpushbutton.h>
#include <qcombobox.h>
#include <qlineedit.h>
#include <qbuttongroup.h>
#include "MySpinBox.h"

class FromToEntryPageData : public QDialog
{
    Q_OBJECT

public:

    FromToEntryPageData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

//  virtual ~FromToEntryPageData();

public slots:


protected slots:


protected:
    QButtonGroup* direc_label;
    QLabel* grade_label;
    QComboBox* gradebox;
    QLabel* fauxami_label;
    QLineEdit* fauxami_line;
    QPushButton* today;
    QPushButton* never;
    QLabel* qcount_label;
    QLineEdit* qcount_line;
    QLabel* bcount_label;
    QLineEdit* bcount_line;
    MySpinBox* year_spin;
    MySpinBox* month_spin;
    MySpinBox* day_spin;

};

#endif // FromToEntryPageData_included
