/**********************************************************************

	--- Qt Architect generated file ---

	File: FromToEntryPageData.cpp
	Last generated: Fri Oct 5 18:15:01 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "FromToEntryPageData.h"

#define Inherited QDialog

#include <qbuttongroup.h>
#include <kapp.h>  // i18n macro

#include <compat_2x.h> // string type macro 


FromToEntryPageData::FromToEntryPageData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	direc_label = new QButtonGroup( this, "ButtonGroup_15" );
	direc_label->setGeometry( 10, 10, 580, 390 );
	direc_label->setFrameStyle( 49 );
	direc_label->setTitle( i18n( "Properties from original" ));
	direc_label->setAlignment( 1 );

	QButtonGroup* qtarch_ButtonGroup_18;
	qtarch_ButtonGroup_18 = new QButtonGroup( this, "ButtonGroup_18" );
	qtarch_ButtonGroup_18->setGeometry( 30, 290, 540, 90 );
	qtarch_ButtonGroup_18->setFrameStyle( 49 );
	qtarch_ButtonGroup_18->setTitle( i18n( "Query counters" ));
	qtarch_ButtonGroup_18->setAlignment( 1 );

	QButtonGroup* qtarch_ButtonGroup_17;
	qtarch_ButtonGroup_17 = new QButtonGroup( this, "ButtonGroup_17" );
	qtarch_ButtonGroup_17->setGeometry( 30, 190, 540, 80 );
	qtarch_ButtonGroup_17->setFrameStyle( 49 );
	qtarch_ButtonGroup_17->setTitle( i18n( "Last query date" ));
	qtarch_ButtonGroup_17->setAlignment( 1 );

	grade_label = new QLabel( this, "Label_23" );
	grade_label->setGeometry( 30, 40, 110, 20 );
	grade_label->setFrameStyle( 0 );
	grade_label->setText( i18n( "&Grade" ));
	grade_label->setAlignment( 289 );

	gradebox = new QComboBox( FALSE, this, "ComboBox_1" );
	gradebox->setGeometry( 30, 60, 240, 30 );
	gradebox->setSizeLimit( 10 );
	gradebox->setAutoResize( FALSE );
	gradebox->setMaxCount( 2147483647 );
	gradebox->setAutoCompletion( FALSE );

	fauxami_label = new QLabel( this, "Label_28" );
	fauxami_label->setGeometry( 30, 110, 270, 20 );
	fauxami_label->setFrameStyle( 0 );
	fauxami_label->setText( i18n( "Fau&x ami" ));
	fauxami_label->setAlignment( 289 );

	fauxami_line = new QLineEdit( this, "LineEdit_14" );
	fauxami_line->setGeometry( 30, 130, 540, 30 );
	fauxami_line->setText( "" );
	fauxami_line->setMaxLength( 32767 );

	today = new QPushButton( this, "PushButton_1" );
	today->setGeometry( 340, 220, 100, 30 );
	today->setText( i18n( "T&oday" ));

	never = new QPushButton( this, "PushButton_2" );
	never->setGeometry( 450, 220, 100, 30 );
	never->setText( i18n( "&Never" ));

	qcount_label = new QLabel( this, "Label_2" );
	qcount_label->setGeometry( 70, 310, 160, 20 );
	qcount_label->setFrameStyle( 0 );
	qcount_label->setText( i18n( "&altogether" ));
	qcount_label->setAlignment( 289 );

	qcount_line = new QLineEdit( this, "LineEdit_4" );
	qcount_line->setGeometry( 70, 330, 160, 30 );
	qcount_line->setText( "" );
	qcount_line->setMaxLength( 32767 );

	bcount_label = new QLabel( this, "Label_22" );
	bcount_label->setGeometry( 360, 310, 160, 20 );
	bcount_label->setFrameStyle( 0 );
	bcount_label->setText( i18n( "&wrong" ));
	bcount_label->setAlignment( 289 );

	bcount_line = new QLineEdit( this, "LineEdit_5" );
	bcount_line->setGeometry( 360, 330, 160, 30 );
	bcount_line->setText( "" );
	bcount_line->setMaxLength( 32767 );

	year_spin = new MySpinBox( this, "User_1" );
	year_spin->setGeometry( 50, 220, 60, 30 );

	month_spin = new MySpinBox( this, "User_2" );
	month_spin->setGeometry( 120, 220, 130, 30 );

	day_spin = new MySpinBox( this, "User_3" );
	day_spin->setGeometry( 260, 220, 60, 30 );




	resize( 600,410 );
}


//FromToEntryPageData::~FromToEntryPageData()
//{
//}
#include "FromToEntryPageData.moc"
