/**********************************************************************

	--- Qt Architect generated file ---

	File: TenseEntryPageData.cpp
	Last generated: Thu Oct 4 17:25:16 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "TenseEntryPageData.h"

#define Inherited QDialog

#include <qlabel.h>
#include <qbuttongroup.h>
#include <kapp.h>  // i18n macro

#include <compat_2x.h> // string type macro 


TenseEntryPageData::TenseEntryPageData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	QButtonGroup* qtarch_ButtonGroup_15;
	qtarch_ButtonGroup_15 = new QButtonGroup( this, "ButtonGroup_15" );
	qtarch_ButtonGroup_15->setGeometry( 10, 10, 580, 390 );
	qtarch_ButtonGroup_15->setFrameStyle( 49 );
	qtarch_ButtonGroup_15->setTitle( i18n( "Conjugation of verbs" ));
	qtarch_ButtonGroup_15->setAlignment( 1 );

	tenselabel = new QLabel( this, "Label_53" );
	tenselabel->setGeometry( 30, 40, 180, 30 );
	tenselabel->setFrameStyle( 0 );
	tenselabel->setText( i18n( "&Tense" ));
	tenselabel->setAlignment( 289 );

	tensebox = new QComboBox( FALSE, this, "ComboBox_1" );
	tensebox->setGeometry( 30, 70, 420, 30 );
	tensebox->setSizeLimit( 10 );
	tensebox->setAutoResize( FALSE );
	tensebox->setMaxCount( 2147483647 );
	tensebox->setAutoCompletion( FALSE );

	b_next = new QPushButton( this, "PushButton_1" );
	b_next->setGeometry( 470, 70, 100, 30 );
	b_next->setText( i18n( "Ne&xt" ));

	QLabel* qtarch_Label_34;
	qtarch_Label_34 = new QLabel( this, "Label_34" );
	qtarch_Label_34->setGeometry( 130, 120, 140, 20 );
	qtarch_Label_34->setFrameStyle( 0 );
	qtarch_Label_34->setText( i18n( "singular" ));
	qtarch_Label_34->setAlignment( 289 );

	QLabel* qtarch_Label_35;
	qtarch_Label_35 = new QLabel( this, "Label_35" );
	qtarch_Label_35->setGeometry( 360, 120, 150, 20 );
	qtarch_Label_35->setFrameStyle( 0 );
	qtarch_Label_35->setText( i18n( "plural" ));
	qtarch_Label_35->setAlignment( 289 );

	pers1_label = new QLabel( this, "Label_33" );
	pers1_label->setGeometry( 30, 150, 90, 30 );
	pers1_label->setFrameStyle( 0 );
	pers1_label->setText( i18n( "&1. person:" ));
	pers1_label->setAlignment( 289 );

	first_singular = new QLineEdit( this, "LineEdit_8" );
	first_singular->setGeometry( 130, 150, 210, 30 );
	first_singular->setText( "" );
	first_singular->setMaxLength( 32767 );

	pers2_label = new QLabel( this, "Label_36" );
	pers2_label->setGeometry( 30, 190, 90, 30 );
	pers2_label->setFrameStyle( 0 );
	pers2_label->setText( i18n( "&2. person:" ));
	pers2_label->setAlignment( 289 );

	second_singular = new QLineEdit( this, "LineEdit_10" );
	second_singular->setGeometry( 130, 190, 210, 30 );
	second_singular->setText( "" );
	second_singular->setMaxLength( 32767 );

	pers3_label = new QLabel( this, "Label_37" );
	pers3_label->setGeometry( 30, 240, 90, 20 );
	pers3_label->setFrameStyle( 0 );
	pers3_label->setText( i18n( "&3. person:" ));
	pers3_label->setAlignment( 289 );

	third_s_common = new QCheckBox( this, "CheckBox_1" );
	third_s_common->setGeometry( 130, 240, 160, 20 );
	third_s_common->setText( i18n( "&common" ));
	third_s_common->setChecked( FALSE );

	female_label = new QLabel( this, "Label_54" );
	female_label->setGeometry( 40, 260, 80, 30 );
	female_label->setFrameStyle( 0 );
	female_label->setText( i18n( "&female" ));
	female_label->setAlignment( 289 );

	thirdF_singular = new QLineEdit( this, "LineEdit_11" );
	thirdF_singular->setGeometry( 130, 260, 210, 30 );
	thirdF_singular->setText( "" );
	thirdF_singular->setMaxLength( 32767 );

	male_label = new QLabel( this, "Label_55" );
	male_label->setGeometry( 40, 300, 80, 30 );
	male_label->setFrameStyle( 0 );
	male_label->setText( i18n( "&male" ));
	male_label->setAlignment( 289 );

	thirdM_singular = new QLineEdit( this, "LineEdit_20" );
	thirdM_singular->setGeometry( 130, 300, 210, 30 );
	thirdM_singular->setText( "" );
	thirdM_singular->setMaxLength( 32767 );

	natural_label = new QLabel( this, "Label_56" );
	natural_label->setGeometry( 40, 340, 80, 30 );
	natural_label->setFrameStyle( 0 );
	natural_label->setText( i18n( "&neutral" ));
	natural_label->setAlignment( 289 );

	thirdN_singular = new QLineEdit( this, "LineEdit_18" );
	thirdN_singular->setGeometry( 130, 340, 210, 30 );
	thirdN_singular->setText( "" );
	thirdN_singular->setMaxLength( 32767 );

	first_plural = new QLineEdit( this, "LineEdit_9" );
	first_plural->setGeometry( 360, 150, 210, 30 );
	first_plural->setText( "" );
	first_plural->setMaxLength( 32767 );

	second_plural = new QLineEdit( this, "LineEdit_12" );
	second_plural->setGeometry( 360, 190, 210, 30 );
	second_plural->setText( "" );
	second_plural->setMaxLength( 32767 );

	third_p_common = new QCheckBox( this, "CheckBox_2" );
	third_p_common->setGeometry( 360, 240, 160, 20 );
	third_p_common->setText( i18n( "c&ommon" ));
	third_p_common->setChecked( FALSE );

	thirdF_plural = new QLineEdit( this, "LineEdit_13" );
	thirdF_plural->setGeometry( 360, 260, 210, 30 );
	thirdF_plural->setText( "" );
	thirdF_plural->setMaxLength( 32767 );

	thirdM_plural = new QLineEdit( this, "LineEdit_21" );
	thirdM_plural->setGeometry( 360, 300, 210, 30 );
	thirdM_plural->setText( "" );
	thirdM_plural->setMaxLength( 32767 );

	thirdN_plural = new QLineEdit( this, "LineEdit_22" );
	thirdN_plural->setGeometry( 360, 340, 210, 30 );
	thirdN_plural->setText( "" );
	thirdN_plural->setMaxLength( 32767 );


	resize( 600,410 );
}


//TenseEntryPageData::~TenseEntryPageData()
//{
//}
