/**********************************************************************

	--- Qt Architect generated file ---

	File: TenseEntryPageData.h
	Last generated: Thu Oct 4 17:25:16 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef TenseEntryPageData_included
#define TenseEntryPageData_included

#include <compat_2x.h> // string type macro 

#ifdef EA_KDE2x
#define EA_SPINBOX_H <qspinbox.h>
#define EA_SPINBOX   QSpinBox
#else
#define EA_SPINBOX_H <kspinbox.h>
#define EA_SPINBOX   KSpinBox
#endif
#include <qdialog.h>
#include <qlabel.h>
#include <qcheckbox.h>
#include <qpushbutton.h>
#include <qcombobox.h>
#include <qlineedit.h>

class TenseEntryPageData : public QDialog
{
    Q_OBJECT

public:

    TenseEntryPageData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

//  virtual ~TenseEntryPageData();

public slots:


protected slots:


protected:
    QLabel* tenselabel;
    QComboBox* tensebox;
    QPushButton* b_next;
    QLabel* pers1_label;
    QLineEdit* first_singular;
    QLabel* pers2_label;
    QLineEdit* second_singular;
    QLabel* pers3_label;
    QCheckBox* third_s_common;
    QLabel* female_label;
    QLineEdit* thirdF_singular;
    QLabel* male_label;
    QLineEdit* thirdM_singular;
    QLabel* natural_label;
    QLineEdit* thirdN_singular;
    QLineEdit* first_plural;
    QLineEdit* second_plural;
    QCheckBox* third_p_common;
    QLineEdit* thirdF_plural;
    QLineEdit* thirdM_plural;
    QLineEdit* thirdN_plural;

};

#endif // TenseEntryPageData_included
