/**********************************************************************

	--- Qt Architect generated file ---

	File: TitlePageData.cpp
	Last generated: Sun Sep 30 11:33:50 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "TitlePageData.h"

#define Inherited QDialog

#include <kapp.h>  // i18n macro

#include <compat_2x.h> // string type macro 


TitlePageData::TitlePageData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	tiltle_group = new QButtonGroup( this, "ButtonGroup_10" );
	tiltle_group->setGeometry( 10, 10, 580, 350 );
	tiltle_group->setFrameStyle( 49 );
	tiltle_group->setTitle( i18n( "General document properties" ));
	tiltle_group->setAlignment( 1 );

	e_title = new QLineEdit( this, "LineEdit_1" );
	e_title->setGeometry( 30, 60, 540, 30 );
	e_title->setText( "" );
	e_title->setMaxLength( 32767 );

	label_title = new QLabel( this, "Label_1" );
	label_title->setGeometry( 30, 40, 350, 20 );
	label_title->setFrameStyle( 0 );
	label_title->setText( i18n( "&Title" ));
	label_title->setAlignment( 289 );

	label_author = new QLabel( this, "Label_2" );
	label_author->setGeometry( 30, 100, 350, 20 );
	label_author->setFrameStyle( 0 );
	label_author->setText( i18n( "&Authors" ));
	label_author->setAlignment( 289 );

	e_license = new QLineEdit( this, "LineEdit_3" );
	e_license->setGeometry( 30, 210, 540, 30 );
	e_license->setText( "" );
	e_license->setMaxLength( 32767 );

	label_license = new QLabel( this, "Label_3" );
	label_license->setGeometry( 30, 190, 350, 20 );
	label_license->setFrameStyle( 0 );
	label_license->setText( i18n( "&License" ));
	label_license->setAlignment( 289 );

	label_remark = new QLabel( this, "Label_4" );
	label_remark->setGeometry( 30, 260, 350, 20 );
	label_remark->setFrameStyle( 0 );
	label_remark->setText( i18n( "&Remark" ));
	label_remark->setAlignment( 289 );

	e_remark = new QMultiLineEdit( this, "MultiLineEdit_1" );
	e_remark->setGeometry( 30, 280, 540, 60 );
	e_remark->setFrameStyle( 51 );
	e_remark->insertLine( "" );
	e_remark->setReadOnly( FALSE );
	e_remark->setOverwriteMode( FALSE );
	e_remark->setAutoUpdate( TRUE );

	e_author = new QMultiLineEdit( this, "MultiLineEdit_2" );
	e_author->setGeometry( 30, 120, 540, 60 );
	e_author->setFrameStyle( 51 );
	e_author->insertLine( "" );
	e_author->setReadOnly( FALSE );
	e_author->setOverwriteMode( FALSE );
	e_author->setAutoUpdate( TRUE );


	resize( 600,370 );
}


//TitlePageData::~TitlePageData()
//{
//}
