/**********************************************************************

	--- Qt Architect generated file ---

	File: TypeOptPageData.h
	Last generated: Sun Sep 30 11:33:49 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef TypeOptPageData_included
#define TypeOptPageData_included

#include <compat_2x.h> // string type macro 

#ifdef EA_KDE2x
#define EA_SPINBOX_H <qspinbox.h>
#define EA_SPINBOX   QSpinBox
#else
#define EA_SPINBOX_H <kspinbox.h>
#define EA_SPINBOX   KSpinBox
#endif
#include <qdialog.h>
#include <qpushbutton.h>
#include <qlistbox.h>
#include <qbuttongroup.h>

class TypeOptPageData : public QDialog
{
    Q_OBJECT

public:

    TypeOptPageData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

//  virtual ~TypeOptPageData();

public slots:


protected slots:


protected:
    QButtonGroup* type_group;
    QListBox* typeList;
    QPushButton* b_new;
    QPushButton* b_modify;
    QPushButton* b_delete;
    QPushButton* b_cleanup;

};

#endif // TypeOptPageData_included
