/**********************************************************************

	--- Qt Architect generated file ---

	File: DocOptionsPageData.cpp
	Last generated: Thu Oct 4 17:26:41 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "DocOptionsPageData.h"

#define Inherited QDialog

#include <qbuttongroup.h>
#include <kapp.h>  // i18n macro

#include <compat_2x.h> // string type macro 


DocOptionsPageData::DocOptionsPageData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	QButtonGroup* qtarch_ButtonGroup_11;
	qtarch_ButtonGroup_11 = new QButtonGroup( this, "ButtonGroup_11" );
	qtarch_ButtonGroup_11->setGeometry( 10, 10, 580, 350 );
	qtarch_ButtonGroup_11->setFrameStyle( 49 );
	qtarch_ButtonGroup_11->setTitle( i18n( "Document options" ));
	qtarch_ButtonGroup_11->setAlignment( 1 );

	docsort = new QCheckBox( this, "CheckBox_1" );
	docsort->setGeometry( 50, 60, 130, 30 );
	docsort->setText( i18n( "allo&w sorting" ));
	docsort->setChecked( FALSE );

	c_coding = new QComboBox( FALSE, this, "ComboBox_1" );
	c_coding->setGeometry( 260, 60, 250, 30 );
	c_coding->setSizeLimit( 10 );
	c_coding->setAutoResize( FALSE );
	c_coding->setMaxCount( 2147483647 );
	c_coding->setAutoCompletion( FALSE );

	l_coding = new QLabel( this, "Label_1" );
	l_coding->setGeometry( 260, 40, 100, 20 );
	l_coding->setFrameStyle( 0 );
	l_coding->setText( i18n( "En&coding" ));
	l_coding->setAlignment( 289 );


	resize( 600,370 );
}


//DocOptionsPageData::~DocOptionsPageData()
//{
//}
#include "DocOptionsPageData.moc"
