/**********************************************************************

	--- Qt Architect generated file ---

	File: LangPropPageData.cpp
	Last generated: Sat Oct 13 18:35:02 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "LangPropPageData.h"

#define Inherited QDialog

#include <qlabel.h>
#include <qbuttongroup.h>
#include <kapp.h>  // i18n macro

#include <compat_2x.h> // string type macro 


LangPropPageData::LangPropPageData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	QButtonGroup* qtarch_ButtonGroup_13;
	qtarch_ButtonGroup_13 = new QButtonGroup( this, "ButtonGroup_13" );
	qtarch_ButtonGroup_13->setGeometry( 10, 10, 580, 350 );
	qtarch_ButtonGroup_13->setFrameStyle( 49 );
	qtarch_ButtonGroup_13->setTitle( i18n( "Language elements" ));
	qtarch_ButtonGroup_13->setAlignment( 1 );

	QButtonGroup* qtarch_ButtonGroup_14;
	qtarch_ButtonGroup_14 = new QButtonGroup( this, "ButtonGroup_14" );
	qtarch_ButtonGroup_14->setGeometry( 30, 40, 230, 200 );
	qtarch_ButtonGroup_14->setFrameStyle( 49 );
	qtarch_ButtonGroup_14->setTitle( i18n( "Articles" ));
	qtarch_ButtonGroup_14->setAlignment( 1 );

	QLabel* qtarch_Label_2;
	qtarch_Label_2 = new QLabel( this, "Label_2" );
	qtarch_Label_2->setGeometry( 110, 60, 60, 20 );
	qtarch_Label_2->setFrameStyle( 0 );
	qtarch_Label_2->setText( i18n( "definite" ));
	qtarch_Label_2->setAlignment( 289 );

	QLabel* qtarch_Label_3;
	qtarch_Label_3 = new QLabel( this, "Label_3" );
	qtarch_Label_3->setGeometry( 180, 60, 70, 20 );
	qtarch_Label_3->setFrameStyle( 0 );
	qtarch_Label_3->setText( i18n( "indefinite" ));
	qtarch_Label_3->setAlignment( 289 );

	female_label = new QLabel( this, "Label_4" );
	female_label->setGeometry( 40, 90, 70, 30 );
	female_label->setFrameStyle( 0 );
	female_label->setText( i18n( "&female:" ));
	female_label->setAlignment( 289 );

	def_female = new QLineEdit( this, "LineEdit_1" );
	def_female->setGeometry( 110, 90, 50, 30 );
	def_female->setText( "" );
	def_female->setMaxLength( 32767 );

	indef_female = new QLineEdit( this, "LineEdit_3" );
	indef_female->setGeometry( 180, 90, 50, 30 );
	indef_female->setText( "" );
	indef_female->setMaxLength( 32767 );

	male_label = new QLabel( this, "Label_5" );
	male_label->setGeometry( 40, 140, 70, 30 );
	male_label->setFrameStyle( 0 );
	male_label->setText( i18n( "&male:" ));
	male_label->setAlignment( 289 );

	def_male = new QLineEdit( this, "LineEdit_4" );
	def_male->setGeometry( 110, 140, 50, 30 );
	def_male->setText( "" );
	def_male->setMaxLength( 32767 );

	indef_male = new QLineEdit( this, "LineEdit_6" );
	indef_male->setGeometry( 180, 140, 50, 30 );
	indef_male->setText( "" );
	indef_male->setMaxLength( 32767 );

	natural_label = new QLabel( this, "Label_6" );
	natural_label->setGeometry( 40, 190, 70, 30 );
	natural_label->setFrameStyle( 0 );
	natural_label->setText( i18n( "&neutral:" ));
	natural_label->setAlignment( 289 );

	def_natural = new QLineEdit( this, "LineEdit_5" );
	def_natural->setGeometry( 110, 190, 50, 30 );
	def_natural->setText( "" );
	def_natural->setMaxLength( 32767 );

	indef_natural = new QLineEdit( this, "LineEdit_7" );
	indef_natural->setGeometry( 180, 190, 50, 30 );
	indef_natural->setText( "" );
	indef_natural->setMaxLength( 32767 );

	QButtonGroup* qtarch_ButtonGroup_15;
	qtarch_ButtonGroup_15 = new QButtonGroup( this, "ButtonGroup_15" );
	qtarch_ButtonGroup_15->setGeometry( 280, 40, 290, 300 );
	qtarch_ButtonGroup_15->setFrameStyle( 49 );
	qtarch_ButtonGroup_15->setTitle( i18n( "Conjugation" ));
	qtarch_ButtonGroup_15->setAlignment( 1 );

	QLabel* qtarch_Label_34;
	qtarch_Label_34 = new QLabel( this, "Label_34" );
	qtarch_Label_34->setGeometry( 380, 70, 80, 20 );
	qtarch_Label_34->setFrameStyle( 0 );
	qtarch_Label_34->setText( i18n( "singular" ));
	qtarch_Label_34->setAlignment( 289 );

	QLabel* qtarch_Label_35;
	qtarch_Label_35 = new QLabel( this, "Label_35" );
	qtarch_Label_35->setGeometry( 470, 70, 80, 20 );
	qtarch_Label_35->setFrameStyle( 0 );
	qtarch_Label_35->setText( i18n( "plural" ));
	qtarch_Label_35->setAlignment( 289 );

	pers1_label = new QLabel( this, "Label_33" );
	pers1_label->setGeometry( 300, 100, 70, 30 );
	pers1_label->setFrameStyle( 0 );
	pers1_label->setText( i18n( "&1. person:" ));
	pers1_label->setAlignment( 289 );

	first_singular = new QLineEdit( this, "LineEdit_8" );
	first_singular->setGeometry( 380, 100, 80, 30 );
	first_singular->setText( "" );
	first_singular->setMaxLength( 32767 );

	first_plural = new QLineEdit( this, "LineEdit_9" );
	first_plural->setGeometry( 470, 100, 80, 30 );
	first_plural->setText( "" );
	first_plural->setMaxLength( 32767 );

	pers2_label = new QLabel( this, "Label_36" );
	pers2_label->setGeometry( 300, 140, 70, 30 );
	pers2_label->setFrameStyle( 0 );
	pers2_label->setText( i18n( "&2. person:" ));
	pers2_label->setAlignment( 289 );

	second_singular = new QLineEdit( this, "LineEdit_10" );
	second_singular->setGeometry( 380, 140, 80, 30 );
	second_singular->setText( "" );
	second_singular->setMaxLength( 32767 );

	second_plural = new QLineEdit( this, "LineEdit_12" );
	second_plural->setGeometry( 470, 140, 80, 30 );
	second_plural->setText( "" );
	second_plural->setMaxLength( 32767 );

	pers3_label = new QLabel( this, "Label_37" );
	pers3_label->setGeometry( 300, 190, 70, 20 );
	pers3_label->setFrameStyle( 0 );
	pers3_label->setText( i18n( "&3. person:" ));
	pers3_label->setAlignment( 289 );

	thirdS_common = new QCheckBox( this, "CheckBox_1" );
	thirdS_common->setGeometry( 380, 190, 80, 20 );
	thirdS_common->setText( i18n( "&common" ));
	thirdS_common->setChecked( FALSE );

	thirdP_common = new QCheckBox( this, "CheckBox_2" );
	thirdP_common->setGeometry( 470, 190, 90, 20 );
	thirdP_common->setText( i18n( "c&ommon" ));
	thirdP_common->setChecked( FALSE );

	female_c_label = new QLabel( this, "Label_67" );
	female_c_label->setGeometry( 310, 210, 60, 30 );
	female_c_label->setFrameStyle( 0 );
	female_c_label->setText( i18n( "f&emale:" ));
	female_c_label->setAlignment( 289 );

	thirdF_singular = new QLineEdit( this, "LineEdit_11" );
	thirdF_singular->setGeometry( 380, 210, 80, 30 );
	thirdF_singular->setText( "" );
	thirdF_singular->setMaxLength( 32767 );

	thirdF_plural = new QLineEdit( this, "LineEdit_13" );
	thirdF_plural->setGeometry( 470, 210, 80, 30 );
	thirdF_plural->setText( "" );
	thirdF_plural->setMaxLength( 32767 );

	male_c_label = new QLabel( this, "Label_68" );
	male_c_label->setGeometry( 310, 250, 60, 30 );
	male_c_label->setFrameStyle( 0 );
	male_c_label->setText( i18n( "m&ale:" ));
	male_c_label->setAlignment( 289 );

	thirdM_singular = new QLineEdit( this, "LineEdit_20" );
	thirdM_singular->setGeometry( 380, 250, 80, 30 );
	thirdM_singular->setText( "" );
	thirdM_singular->setMaxLength( 32767 );

	thirdM_plural = new QLineEdit( this, "LineEdit_21" );
	thirdM_plural->setGeometry( 470, 250, 80, 30 );
	thirdM_plural->setText( "" );
	thirdM_plural->setMaxLength( 32767 );

	natural_c_label = new QLabel( this, "Label_69" );
	natural_c_label->setGeometry( 310, 290, 60, 30 );
	natural_c_label->setFrameStyle( 0 );
	natural_c_label->setText( i18n( "neu&tral:" ));
	natural_c_label->setAlignment( 289 );

	thirdN_singular = new QLineEdit( this, "LineEdit_18" );
	thirdN_singular->setGeometry( 380, 290, 80, 30 );
	thirdN_singular->setText( "" );
	thirdN_singular->setMaxLength( 32767 );

	thirdN_plural = new QLineEdit( this, "LineEdit_22" );
	thirdN_plural->setGeometry( 470, 290, 80, 30 );
	thirdN_plural->setText( "" );
	thirdN_plural->setMaxLength( 32767 );

#if QT_VERSION < 300
	charset_box = new QComboBox( FALSE, this, "ComboBox_1" );
	charset_box->setGeometry( 30, 290, 230, 30 );
	charset_box->setSizeLimit( 10 );
	charset_box->setAutoResize( FALSE );
	charset_box->setMaxCount( 2147483647 );
	charset_box->setAutoCompletion( FALSE );

	charset_label = new QLabel( this, "Label_70" );
	charset_label->setGeometry( 30, 260, 220, 30 );
	charset_label->setFrameStyle( 0 );
	charset_label->setText( i18n( "Re&quired charset" ));
	charset_label->setAlignment( 289 );
#endif

	resize( 600,370 );
}


//LangPropPageData::~LangPropPageData()
//{
//}

#include "LangPropPageData.moc"
