/**********************************************************************

	--- Qt Architect generated file ---

	File: LangPropPageData.h
	Last generated: Sat Oct 13 18:35:02 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef LangPropPageData_included
#define LangPropPageData_included

#include <compat_2x.h> // string type macro 

#ifdef EA_KDE2x
#define EA_SPINBOX_H <qspinbox.h>
#define EA_SPINBOX   QSpinBox
#else
#define EA_SPINBOX_H <kspinbox.h>
#define EA_SPINBOX   KSpinBox
#endif
#include <qdialog.h>
#include <qlabel.h>
#include <qcheckbox.h>
#include <qcombobox.h>
#include <qlineedit.h>

class LangPropPageData : public QDialog
{
    Q_OBJECT

public:

    LangPropPageData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

//  virtual ~LangPropPageData();

public slots:


protected slots:


protected:
    QLabel* female_label;
    QLineEdit* def_female;
    QLineEdit* indef_female;
    QLabel* male_label;
    QLineEdit* def_male;
    QLineEdit* indef_male;
    QLabel* natural_label;
    QLineEdit* def_natural;
    QLineEdit* indef_natural;
    QLabel* pers1_label;
    QLineEdit* first_singular;
    QLineEdit* first_plural;
    QLabel* pers2_label;
    QLineEdit* second_singular;
    QLineEdit* second_plural;
    QLabel* pers3_label;
    QCheckBox* thirdS_common;
    QCheckBox* thirdP_common;
    QLabel* female_c_label;
    QLineEdit* thirdF_singular;
    QLineEdit* thirdF_plural;
    QLabel* male_c_label;
    QLineEdit* thirdM_singular;
    QLineEdit* thirdM_plural;
    QLabel* natural_c_label;
    QLineEdit* thirdN_singular;
    QLineEdit* thirdN_plural;
    QComboBox* charset_box;
    QLabel* charset_label;

};

#endif // LangPropPageData_included
