/**********************************************************************

	--- Qt Architect generated file ---

	File: TenseOptPageData.h
	Last generated: Sat Oct 13 18:34:55 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef TenseOptPageData_included
#define TenseOptPageData_included

#include <compat_2x.h> // string type macro 

#ifdef EA_KDE2x
#define EA_SPINBOX_H <qspinbox.h>
#define EA_SPINBOX   QSpinBox
#else
#define EA_SPINBOX_H <kspinbox.h>
#define EA_SPINBOX   KSpinBox
#endif
#include <qdialog.h>
#include <qpushbutton.h>
#include <qlistbox.h>
#include <qbuttongroup.h>

class TenseOptPageData : public QDialog
{
    Q_OBJECT

public:

    TenseOptPageData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

//  virtual ~TenseOptPageData();

public slots:


protected slots:


protected:
    QButtonGroup* tense_group;
    QListBox* tenseList;
    QPushButton* b_new;
    QPushButton* b_modify;
    QPushButton* b_delete;
    QPushButton* b_cleanup;

};

#endif // TenseOptPageData_included
