/**********************************************************************

	--- Qt Architect generated file ---

	File: TenseOptPageData.cpp
	Last generated: Thu Oct 4 17:26:37 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "TenseOptPageData.h"

#define Inherited QDialog

#include <kapp.h>  // i18n macro

#include <compat_2x.h> // string type macro 


TenseOptPageData::TenseOptPageData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	tense_group = new QButtonGroup( this, "ButtonGroup_10" );
	tense_group->setGeometry( 10, 10, 580, 350 );
	tense_group->setFrameStyle( 49 );
	tense_group->setTitle( i18n( "Tense Descriptions" ));
	tense_group->setAlignment( 1 );

	tenseList = new QListBox( this, "ListBox_1" );
	tenseList->setGeometry( 20, 30, 560, 280 );
	tenseList->setFrameStyle( 51 );
	tenseList->setDragSelect( TRUE );
	tenseList->setAutoScroll( TRUE );
	tenseList->setScrollBar( FALSE );
	tenseList->setAutoScrollBar( TRUE );
	tenseList->setBottomScrollBar( FALSE );
	tenseList->setAutoBottomScrollBar( TRUE );
	tenseList->setSmoothScrolling( TRUE );
	tenseList->setMultiSelection( FALSE );
	tenseList->setAutoUpdate( TRUE );

	b_new = new QPushButton( this, "PushButton_22" );
	b_new->setGeometry( 20, 320, 80, 30 );
	b_new->setText( i18n( "&New" ));

	b_modify = new QPushButton( this, "PushButton_23" );
	b_modify->setGeometry( 110, 320, 80, 30 );
	b_modify->setText( i18n( "&Modify" ));

	b_delete = new QPushButton( this, "PushButton_24" );
	b_delete->setGeometry( 200, 320, 80, 30 );
	b_delete->setText( i18n( "&Delete" ));

	b_cleanup = new QPushButton( this, "PushButton_25" );
	b_cleanup->setGeometry( 500, 320, 80, 30 );
	b_cleanup->setText( i18n( "&Clean up" ));


	resize( 600,370 );
}


//TenseOptPageData::~TenseOptPageData()
//{
//}
