/**********************************************************************

	--- Qt Architect generated file ---

	File: TitlePageData.h
	Last generated: Thu Oct 4 17:26:31 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef TitlePageData_included
#define TitlePageData_included

#include <compat_2x.h> // string type macro 

#ifdef EA_KDE2x
#define EA_SPINBOX_H <qspinbox.h>
#define EA_SPINBOX   QSpinBox
#else
#define EA_SPINBOX_H <kspinbox.h>
#define EA_SPINBOX   KSpinBox
#endif
#include <qdialog.h>
#include <qlabel.h>
#include <qmultilinedit.h>
#include <qlineedit.h>
#include <qbuttongroup.h>

class TitlePageData : public QDialog
{
    Q_OBJECT

public:

    TitlePageData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

//  virtual ~TitlePageData();

public slots:


protected slots:


protected:
    QButtonGroup* tiltle_group;
    QLineEdit* e_title;
    QLabel* label_title;
    QLabel* label_author;
    QLineEdit* e_license;
    QLabel* label_license;
    QLabel* label_remark;
    QMultiLineEdit* e_remark;
    QMultiLineEdit* e_author;

};

#endif // TitlePageData_included
