/**********************************************************************

	--- Qt Architect generated file ---

	File: UsageOptPageData.cpp
	Last generated: Thu Oct 4 17:26:39 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "UsageOptPageData.h"

#define Inherited QDialog

#include <kapp.h>  // i18n macro

#include <compat_2x.h> // string type macro 


UsageOptPageData::UsageOptPageData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	usage_group = new QButtonGroup( this, "ButtonGroup_10" );
	usage_group->setGeometry( 10, 10, 580, 350 );
	usage_group->setFrameStyle( 49 );
	usage_group->setTitle( i18n( "Usage Labels" ));
	usage_group->setAlignment( 1 );

	usageList = new QListBox( this, "ListBox_1" );
	usageList->setGeometry( 20, 30, 560, 280 );
	usageList->setFrameStyle( 51 );
	usageList->setDragSelect( TRUE );
	usageList->setAutoScroll( TRUE );
	usageList->setScrollBar( FALSE );
	usageList->setAutoScrollBar( TRUE );
	usageList->setBottomScrollBar( FALSE );
	usageList->setAutoBottomScrollBar( TRUE );
	usageList->setSmoothScrolling( TRUE );
	usageList->setMultiSelection( FALSE );
	usageList->setAutoUpdate( TRUE );

	b_new = new QPushButton( this, "PushButton_22" );
	b_new->setGeometry( 20, 320, 80, 30 );
	b_new->setText( i18n( "&New" ));

	b_modify = new QPushButton( this, "PushButton_23" );
	b_modify->setGeometry( 110, 320, 80, 30 );
	b_modify->setText( i18n( "&Modify" ));

	b_delete = new QPushButton( this, "PushButton_24" );
	b_delete->setGeometry( 200, 320, 80, 30 );
	b_delete->setText( i18n( "&Delete" ));

	b_cleanup = new QPushButton( this, "PushButton_25" );
	b_cleanup->setGeometry( 500, 320, 80, 30 );
	b_cleanup->setText( i18n( "&Clean up" ));


	resize( 600,370 );
}


//UsageOptPageData::~UsageOptPageData()
//{
//}
#include "UsageOptPageData.moc"
