/**********************************************************************

	--- Qt Architect generated file ---

	File: GenStatPageData.cpp
	Last generated: Thu Oct 4 17:42:19 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "GenStatPageData.h"

#define Inherited QDialog

#include <qlabel.h>
#include <kapp.h>  // i18n macro

#include <compat_2x.h> // string type macro 


GenStatPageData::GenStatPageData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	QLabel* qtarch_Label_1;
	qtarch_Label_1 = new QLabel( this, "Label_1" );
	qtarch_Label_1->setGeometry( 30, 70, 100, 20 );
	{
		QFont font( "helvetica", 12, 63, 0 );
		font.setStyleHint( (QFont::StyleHint)0 );
		font.setCharSet( (QFont::CharSet)0 );
		qtarch_Label_1->setFont( font );
	}
	qtarch_Label_1->setFrameStyle( 0 );
	qtarch_Label_1->setText( i18n( "Title:" ));
	qtarch_Label_1->setAlignment( 289 );

	QLabel* qtarch_Label_3;
	qtarch_Label_3 = new QLabel( this, "Label_3" );
	qtarch_Label_3->setGeometry( 30, 110, 100, 20 );
	{
		QFont font( "helvetica", 12, 63, 0 );
		font.setStyleHint( (QFont::StyleHint)0 );
		font.setCharSet( (QFont::CharSet)0 );
		qtarch_Label_3->setFont( font );
	}
	qtarch_Label_3->setFrameStyle( 0 );
	qtarch_Label_3->setText( i18n( "Author:" ));
	qtarch_Label_3->setAlignment( 289 );

	QLabel* qtarch_Label_4;
	qtarch_Label_4 = new QLabel( this, "Label_4" );
	qtarch_Label_4->setGeometry( 30, 170, 100, 20 );
	{
		QFont font( "helvetica", 12, 63, 0 );
		font.setStyleHint( (QFont::StyleHint)0 );
		font.setCharSet( (QFont::CharSet)0 );
		qtarch_Label_4->setFont( font );
	}
	qtarch_Label_4->setFrameStyle( 0 );
	qtarch_Label_4->setText( i18n( "Entries:" ));
	qtarch_Label_4->setAlignment( 289 );

	QLabel* qtarch_Label_5;
	qtarch_Label_5 = new QLabel( this, "Label_5" );
	qtarch_Label_5->setGeometry( 30, 210, 100, 20 );
	{
		QFont font( "helvetica", 12, 63, 0 );
		font.setStyleHint( (QFont::StyleHint)0 );
		font.setCharSet( (QFont::CharSet)0 );
		qtarch_Label_5->setFont( font );
	}
	qtarch_Label_5->setFrameStyle( 0 );
	qtarch_Label_5->setText( i18n( "Lessons:" ));
	qtarch_Label_5->setAlignment( 289 );

	QLabel* qtarch_Label_10;
	qtarch_Label_10 = new QLabel( this, "Label_10" );
	qtarch_Label_10->setGeometry( 30, 30, 100, 20 );
	{
		QFont font( "helvetica", 12, 63, 0 );
		font.setStyleHint( (QFont::StyleHint)0 );
		font.setCharSet( (QFont::CharSet)0 );
		qtarch_Label_10->setFont( font );
	}
	qtarch_Label_10->setFrameStyle( 0 );
	qtarch_Label_10->setText( i18n( "Filename:" ));
	qtarch_Label_10->setAlignment( 289 );

	l_filename = new QLabel( this, "Label_11" );
	l_filename->setGeometry( 140, 30, 410, 30 );
	l_filename->setFrameStyle( 50 );
	l_filename->setText( "" );
	l_filename->setAlignment( 289 );

	l_title = new QLabel( this, "Label_12" );
	l_title->setGeometry( 140, 70, 410, 30 );
	l_title->setFrameStyle( 50 );
	l_title->setText( "" );
	l_title->setAlignment( 289 );

	l_author = new QLabel( this, "Label_13" );
	l_author->setGeometry( 140, 110, 410, 50 );
	l_author->setFrameStyle( 50 );
	l_author->setText( "" );
	l_author->setAlignment( 289 );

	l_entries = new QLabel( this, "Label_14" );
	l_entries->setGeometry( 140, 170, 410, 30 );
	l_entries->setFrameStyle( 50 );
	l_entries->setText( "" );
	l_entries->setAlignment( 289 );

	l_lessons = new QLabel( this, "Label_15" );
	l_lessons->setGeometry( 140, 210, 410, 30 );
	l_lessons->setFrameStyle( 50 );
	l_lessons->setText( "" );
	l_lessons->setAlignment( 289 );

	resize( 590,350 );
}


//GenStatPageData::~GenStatPageData()
//{
//}
#include "GenStatPageData.moc"
