/**********************************************************************

	--- Qt Architect generated file ---

	File: GenStatPageData.h
	Last generated: Sat Oct 13 18:39:03 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef GenStatPageData_included
#define GenStatPageData_included

#include <compat_2x.h> // string type macro 

#ifdef EA_KDE2x
#define EA_SPINBOX_H <qspinbox.h>
#define EA_SPINBOX   QSpinBox
#else
#define EA_SPINBOX_H <kspinbox.h>
#define EA_SPINBOX   KSpinBox
#endif
#include <qdialog.h>
#include <qlabel.h>

class GenStatPageData : public QDialog
{
    Q_OBJECT

public:

    GenStatPageData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

//  virtual ~GenStatPageData();

public slots:


protected slots:


protected:
    QLabel* l_filename;
    QLabel* l_title;
    QLabel* l_author;
    QLabel* l_entries;
    QLabel* l_lessons;

};

#endif // GenStatPageData_included
