/**********************************************************************

	--- Qt Architect generated file ---

	File: StatistikPageData.cpp
	Last generated: Sat Oct 13 18:39:01 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "StatistikPageData.h"

#define Inherited QDialog

#include <kapp.h>  // i18n macro

#include <compat_2x.h> // string type macro 


StatistikPageData::StatistikPageData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	num_entry = new QLabel( this, "Label_2" );
	num_entry->setGeometry( 150, 30, 100, 20 );
	num_entry->setFrameStyle( 0 );
	num_entry->setText( "" );
	num_entry->setAlignment( 289 );

	resize( 590,350 );
}


//StatistikPageData::~StatistikPageData()
//{
//}
#include "StatistikPageData.moc"
