/**********************************************************************

	--- Qt Architect generated file ---

	File: BlockOptPageData.h
	Last generated: Thu Oct 4 17:23:25 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef BlockOptPageData_included
#define BlockOptPageData_included

#include <compat_2x.h> // string type macro 

#ifdef EA_KDE2x
#define EA_SPINBOX_H <qspinbox.h>
#define EA_SPINBOX   QSpinBox
#else
#define EA_SPINBOX_H <kspinbox.h>
#define EA_SPINBOX   KSpinBox
#endif
#include <qdialog.h>
#include <qlabel.h>
#include <qcheckbox.h>
#include <qcombobox.h>

class BlockOptPageData : public QDialog
{
    Q_OBJECT

public:

    BlockOptPageData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

//  virtual ~BlockOptPageData();

public slots:


protected slots:


protected:
    QCheckBox* c_blocking;
    QCheckBox* c_expire;
    QLabel* l_lev7;
    QComboBox* block7;
    QComboBox* expire7;
    QLabel* l_lev6;
    QComboBox* block6;
    QComboBox* expire6;
    QLabel* l_lev5;
    QComboBox* block5;
    QComboBox* expire5;
    QLabel* l_lev4;
    QComboBox* block4;
    QComboBox* expire4;
    QLabel* l_lev3;
    QComboBox* block3;
    QComboBox* expire3;
    QLabel* l_lev2;
    QComboBox* block2;
    QComboBox* expire2;
    QLabel* l_lev1;
    QComboBox* block1;
    QComboBox* expire1;

};

#endif // BlockOptPageData_included
