/**********************************************************************

	--- Qt Architect generated file ---

	File: QueryOptPageData.h
	Last generated: Sat Oct 13 21:27:32 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef QueryOptPageData_included
#define QueryOptPageData_included

#include <compat_2x.h> // string type macro 

#ifdef EA_KDE2x
#define EA_SPINBOX_H <qspinbox.h>
#define EA_SPINBOX   QSpinBox
#else
#define EA_SPINBOX_H <kspinbox.h>
#define EA_SPINBOX   KSpinBox
#endif
#include <qdialog.h>
#include <qlabel.h>
#include <qradiobutton.h>
#include <qcheckbox.h>
#include <qlineedit.h>
#include <qbuttongroup.h>

class QueryOptPageData : public QDialog
{
    Q_OBJECT

public:

    QueryOptPageData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

//  virtual ~QueryOptPageData();

public slots:


protected slots:


protected:
    QButtonGroup* query_group;
    QLabel* label_mqtime;
    QLineEdit* e_mqtime;
    QCheckBox* swap;
    QRadioButton* r_show_to;
    QRadioButton* r_cont_to;
    QRadioButton* r_nolimit_to;
    QCheckBox* showrem;

};

#endif // QueryOptPageData_included
