/**********************************************************************

	--- Qt Architect generated file ---

	File: ThreshOptPageData.cpp
	Last generated: Sat Oct 13 21:27:34 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "ThreshOptPageData.h"

#define Inherited QDialog

#include <qbuttongroup.h>
#include <kapp.h>  // i18n macro

#include <compat_2x.h> // string type macro 


ThreshOptPageData::ThreshOptPageData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	QButtonGroup* qtarch_ButtonGroup_1;
	qtarch_ButtonGroup_1 = new QButtonGroup( this, "ButtonGroup_1" );
	qtarch_ButtonGroup_1->setGeometry( 10, 10, 500, 340 );
	qtarch_ButtonGroup_1->setFrameStyle( 49 );
	qtarch_ButtonGroup_1->setTitle( i18n( "Query threshholds" ));
	qtarch_ButtonGroup_1->setAlignment( 1 );

	label_lesson = new QLabel( this, "Label_1" );
	label_lesson->setGeometry( 20, 50, 100, 30 );
	label_lesson->setFrameStyle( 0 );
	label_lesson->setText( i18n( "&Lesson:" ));
	label_lesson->setAlignment( 289 );

	lessoncomp = new QComboBox( FALSE, this, "ComboBox_12" );
	lessoncomp->setGeometry( 130, 50, 160, 30 );
	lessoncomp->setSizeLimit( 10 );
	lessoncomp->setAutoResize( FALSE );
	lessoncomp->setMaxCount( 2147483647 );
	lessoncomp->setAutoCompletion( FALSE );

	label_type = new QLabel( this, "Label_9" );
	label_type->setGeometry( 20, 140, 100, 30 );
	label_type->setFrameStyle( 0 );
	label_type->setText( i18n( "Word t&ype:" ));
	label_type->setAlignment( 289 );

	typecomp = new QComboBox( FALSE, this, "ComboBox_4" );
	typecomp->setGeometry( 130, 140, 160, 30 );
	typecomp->setSizeLimit( 10 );
	typecomp->setAutoResize( FALSE );
	typecomp->setMaxCount( 2147483647 );
	typecomp->setAutoCompletion( FALSE );

	typelist = new QComboBox( FALSE, this, "ComboBox_2" );
	typelist->setGeometry( 300, 140, 190, 30 );
	typelist->setSizeLimit( 10 );
	typelist->setAutoResize( FALSE );
	typelist->setMaxCount( 2147483647 );
	typelist->setAutoCompletion( FALSE );

	label_grade = new QLabel( this, "Label_2" );
	label_grade->setGeometry( 20, 180, 100, 30 );
	label_grade->setFrameStyle( 0 );
	label_grade->setText( i18n( "G&rade:" ));
	label_grade->setAlignment( 289 );

	gradecomp = new QComboBox( FALSE, this, "ComboBox_3" );
	gradecomp->setGeometry( 130, 180, 160, 30 );
	gradecomp->setSizeLimit( 10 );
	gradecomp->setAutoResize( FALSE );
	gradecomp->setMaxCount( 2147483647 );
	gradecomp->setAutoCompletion( FALSE );

	gradelist = new QComboBox( FALSE, this, "ComboBox_6" );
	gradelist->setGeometry( 300, 180, 190, 30 );
	gradelist->setSizeLimit( 10 );
	gradelist->setAutoResize( FALSE );
	gradelist->setMaxCount( 2147483647 );
	gradelist->setAutoCompletion( FALSE );

	label_qcount = new QLabel( this, "Label_4" );
	label_qcount->setGeometry( 20, 220, 100, 30 );
	label_qcount->setFrameStyle( 0 );
	label_qcount->setText( i18n( "Query c&ount:" ));
	label_qcount->setAlignment( 289 );

	querycomp = new QComboBox( FALSE, this, "ComboBox_5" );
	querycomp->setGeometry( 130, 220, 160, 30 );
	querycomp->setSizeLimit( 10 );
	querycomp->setAutoResize( FALSE );
	querycomp->setMaxCount( 2147483647 );
	querycomp->setAutoCompletion( FALSE );

	querylist = new QComboBox( FALSE, this, "ComboBox_8" );
	querylist->setGeometry( 300, 220, 190, 30 );
	querylist->setSizeLimit( 10 );
	querylist->setAutoResize( FALSE );
	querylist->setMaxCount( 2147483647 );
	querylist->setAutoCompletion( FALSE );

	label_bcount = new QLabel( this, "Label_5" );
	label_bcount->setGeometry( 20, 260, 100, 30 );
	label_bcount->setFrameStyle( 0 );
	label_bcount->setText( i18n( "&Bad count:" ));
	label_bcount->setAlignment( 289 );

	badcomp = new QComboBox( FALSE, this, "ComboBox_7" );
	badcomp->setGeometry( 130, 260, 160, 30 );
	badcomp->setSizeLimit( 10 );
	badcomp->setAutoResize( FALSE );
	badcomp->setMaxCount( 2147483647 );
	badcomp->setAutoCompletion( FALSE );

	badlist = new QComboBox( FALSE, this, "ComboBox_11" );
	badlist->setGeometry( 300, 260, 190, 30 );
	badlist->setSizeLimit( 10 );
	badlist->setAutoResize( FALSE );
	badlist->setMaxCount( 2147483647 );
	badlist->setAutoCompletion( FALSE );

	label_qdate = new QLabel( this, "Label_3" );
	label_qdate->setGeometry( 20, 300, 100, 30 );
	label_qdate->setFrameStyle( 0 );
	label_qdate->setText( i18n( "Last q&uery:" ));
	label_qdate->setAlignment( 289 );

	datecomp = new QComboBox( FALSE, this, "ComboBox_9" );
	datecomp->setGeometry( 130, 300, 160, 30 );
	datecomp->setSizeLimit( 10 );
	datecomp->setAutoResize( FALSE );
	datecomp->setMaxCount( 2147483647 );
	datecomp->setAutoCompletion( FALSE );

	datelist = new QComboBox( FALSE, this, "ComboBox_10" );
	datelist->setGeometry( 300, 300, 190, 30 );
	datelist->setSizeLimit( 10 );
	datelist->setAutoResize( FALSE );
	datelist->setMaxCount( 2147483647 );
	datelist->setAutoCompletion( FALSE );

	lessonlist = new QListBox( this, "ListBox_1" );
	lessonlist->setGeometry( 300, 50, 190, 80 );
	lessonlist->setFrameStyle( 51 );
	lessonlist->setDragSelect( TRUE );
	lessonlist->setAutoScroll( TRUE );
	lessonlist->setScrollBar( FALSE );
	lessonlist->setAutoScrollBar( TRUE );
	lessonlist->setBottomScrollBar( FALSE );
	lessonlist->setAutoBottomScrollBar( TRUE );
	lessonlist->setSmoothScrolling( TRUE );
	lessonlist->setMultiSelection( TRUE );
	lessonlist->setAutoUpdate( TRUE );

	l_lesson = new QLabel( this, "Label_45" );
	l_lesson->setGeometry( 310, 30, 130, 20 );
	l_lesson->setFrameStyle( 0 );
	l_lesson->setText( i18n( "Selected lessons:" ));
	l_lesson->setAlignment( 289 );

	l_count = new QLabel( this, "Label_46" );
	l_count->setGeometry( 450, 30, 30, 20 );
	l_count->setFrameStyle( 0 );
	l_count->setText( i18n( "???" ));
	l_count->setAlignment( 289 );

	b_all_less = new QPushButton( this, "PushButton_1" );
	b_all_less->setGeometry( 130, 90, 70, 30 );
	b_all_less->setText( i18n( "&All" ));

	b_none_less = new QPushButton( this, "PushButton_2" );
	b_none_less->setGeometry( 220, 90, 70, 30 );
	b_none_less->setText( i18n( "&None" ));


	resize( 520,360 );
}


//ThreshOptPageData::~ThreshOptPageData()
//{
//}

#include "ThreshOptPageData.moc"
