/**********************************************************************

	--- Qt Architect generated file ---

	File: ThreshOptPageData.h
	Last generated: Thu Oct 4 17:23:23 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef ThreshOptPageData_included
#define ThreshOptPageData_included

#include <compat_2x.h> // string type macro 

#ifdef EA_KDE2x
#define EA_SPINBOX_H <qspinbox.h>
#define EA_SPINBOX   QSpinBox
#else
#define EA_SPINBOX_H <kspinbox.h>
#define EA_SPINBOX   KSpinBox
#endif
#include <qdialog.h>
#include <qlabel.h>
#include <qpushbutton.h>
#include <qcombobox.h>
#include <qlistbox.h>

class ThreshOptPageData : public QDialog
{
    Q_OBJECT

public:

    ThreshOptPageData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

//  virtual ~ThreshOptPageData();

public slots:


protected slots:


protected:
    QLabel* label_lesson;
    QComboBox* lessoncomp;
    QLabel* label_type;
    QComboBox* typecomp;
    QComboBox* typelist;
    QLabel* label_grade;
    QComboBox* gradecomp;
    QComboBox* gradelist;
    QLabel* label_qcount;
    QComboBox* querycomp;
    QComboBox* querylist;
    QLabel* label_bcount;
    QComboBox* badcomp;
    QComboBox* badlist;
    QLabel* label_qdate;
    QComboBox* datecomp;
    QComboBox* datelist;
    QListBox* lessonlist;
    QLabel* l_lesson;
    QLabel* l_count;
    QPushButton* b_all_less;
    QPushButton* b_none_less;

};

#endif // ThreshOptPageData_included
